In [10]:
import pandas as pd

from xgboost import XGBRegressor

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import mean_squared_error, r2_score

import matplotlib.pyplot as plt

In [11]:
import pandas as pd

F_selection = pd.read_csv("F_Selection/top_N_features_PersonsRAll.csv")

# Extract top 10, 20, 30, and 50 features
top_10 = F_selection["Feature"].head(10).tolist()
top_20 = F_selection["Feature"].head(20).tolist()
top_30 = F_selection["Feature"].head(30).tolist()
top_40 = F_selection["Feature"].head(40).tolist()
top_50 = F_selection["Feature"].head(50).tolist()

In [12]:
def Data_Organizer(raw_Data,top):
    
    All_players_dataSet = raw_Data.copy()
    
    All_players_dataSet = All_players_dataSet.drop(columns=All_players_dataSet.columns[All_players_dataSet.columns.str.contains('Unnamed:')])
    All_players_dataSet.reset_index(drop=True, inplace=True)
    
    All_players_dataSet.fillna(0, inplace=True)
    All_players_dataSet.replace('', 0, inplace=True)
    All_players_dataSet.replace('--', 0, inplace=True)
    
    # check if any NaN,empty Strings exists in the dataframe
    any_missing_values = All_players_dataSet.isna().any().any()
    any_empty_values = (All_players_dataSet.applymap(lambda x: x == '')).any().any()
    
    if any_missing_values or any_empty_values:
        print("DataFrame contains missing values or empty strings/spaces.")
    else:
        print("DataFrame does not contain missing values or empty strings/spaces.")
        
    ## seperating our dataFrame
    Y = All_players_dataSet['Points_won']  # Target
    X = All_players_dataSet.drop('Points_won', axis=1)  # Features
    
    X = X.apply(pd.to_numeric, errors='coerce')

    ## keep the specified columns
    columns_to_keep = top
    
    ## keep only wanted columns
    X = X[columns_to_keep]

    return X, Y

In [13]:
all_players_w_add_sorted = pd.read_csv("all_players_w_add_sorted.csv")

C:\Users\Abdou\AppData\Local\Temp\ipykernel_10124\1174582640.py:1: DtypeWarning: Columns (154,155) have mixed types. Specify dtype option on import or set low_memory=False.
  all_players_w_add_sorted = pd.read_csv("all_players_w_add_sorted.csv")

In [14]:
top = top_10

rank_data_10 = pd.DataFrame()

for year in range(1994,2024):
    print("Selected Features Top ",10," Test year : ", year)
    Test_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] == year]
    Train_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] < year]
    
    X_train, y_train = Data_Organizer(Train_Data,top)
    X_test , y_test = Data_Organizer(Test_Data,top)
    
    # Initialize and train a XGBoost Regressor model
    xgb_model = XGBRegressor(n_estimators=200,max_depth = 5, random_state=42, n_jobs=-1)
    xgb_model.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred_xgb = xgb_model.predict(X_test)
    
    # Evaluate the model
    mse_xgb = mean_squared_error(y_test, y_pred_xgb)
    r2_xgb = r2_score(y_test, y_pred_xgb)
    
    # Mean Squared Error (MAE)
    print(f'Mean Squared Error (XGBoost): {mse_xgb}')
    print(f'R-squared (XGBoost): {r2_xgb}')
    
    Test_Data_copy = Test_Data.copy()
    Test_Data_copy.loc[:, 'Predicted_points'] = y_pred_xgb
    
    # Select only the desired columns
    Test_Data_concatenated = Test_Data_copy[['Player_name','Rank','Pos','Points_won', 'Predicted_points']]
    
    # Display the concatenated DataFrame sorted by 'Points_won'
    display(Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10))

    Test_Data_concatenated = Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10)
    
    if rank_data_10.empty:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_10 = pd.DataFrame(new_rank_column)
    else:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_10 = pd.concat([rank_data_10.reset_index(drop=True), new_rank_column.reset_index(drop=True)], axis=1)

    print("---------------------------------------------------------------------")

display(rank_data_10)

Selected Features Top  10  Test year :  1994
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.086077217081475
R-squared (XGBoost): -0.9183968027655238

           Player_name Rank Pos  Points_won  Predicted_points
15651  Hakeem Olajuwon    1   C        23.0         72.997940
15539   David Robinson    2   C        22.0          9.000013
15477   Scottie Pippen    4  SF        11.0          8.998991
15583  Mookie Blaylock   7T  PG         3.0          8.998991
15743  Dikembe Mutombo    3   C        19.0          1.227015
15796      Dan Majerle   -1  SG         0.0          1.226771
15540     Horace Grant   10  PF         1.0          1.226771
15649   Charles Oakley    9  PF         2.0          1.000326
15739    Patrick Ewing   -1   C         0.0          1.000284
15677    Nate McMillan   7T  PG         3.0          1.000082

---------------------------------------------------------------------
Selected Features Top  10  Test year :  1995
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 1.8268852106639022
R-squared (XGBoost): 0.7096281065999412

           Player_name Rank Pos  Points_won  Predicted_points
15026  Dikembe Mutombo    1   C        45.0         18.846771
15113   David Robinson    4   C        12.0         15.254402
15199   Scottie Pippen    2  SF        16.0         15.209162
14994  Hakeem Olajuwon    3   C        13.0         10.494151
15121    Dennis Rodman    5  PF        11.0          5.789373
15249    Nate McMillan   6T  PG         2.0          5.756645
15051    Patrick Ewing   -1   C         0.0          4.268012
15077  Mookie Blaylock   -1  PG         0.0          3.898173
15151      Gary Payton   6T  PG         2.0          2.288019
15358      Dan Majerle   -1  SF         0.0          2.042657

---------------------------------------------------------------------
Selected Features Top  10  Test year :  1996
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 13.187948991033085
R-squared (XGBoost): -0.7577281973577759

           Player_name  Rank Pos  Points_won  Predicted_points
14887  Dikembe Mutombo     3   C        11.0         72.920471
14897   David Robinson     4   C         9.0         14.989509
14619   Michael Jordan     6  SG         7.0         13.894057
14749   Scottie Pippen     2  SF        15.0         12.694979
14909    Dennis Rodman     7  PF         4.0          8.772997
14797  Hakeem Olajuwon     5   C         8.0          7.997690
14838   Charles Oakley    -1  PF         0.0          7.968857
14844      Gary Payton     1  PG        56.0          7.734124
14555     Horace Grant    8T  PF         1.0          7.387488
14839    Shawn Bradley  -1.0   C         0.0          6.984166

---------------------------------------------------------------------
Selected Features Top  10  Test year :  1997
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 5.795285690449885
R-squared (XGBoost): 0.349590743243932

           Player_name  Rank Pos  Points_won  Predicted_points
14149      Gary Payton     2  PG        25.0         27.674763
14081   Michael Jordan     5  SG         3.0         11.852278
14210  Hakeem Olajuwon    -1   C         0.0         11.587030
14489  Dikembe Mutombo     1   C        60.0         10.067729
14279     Horace Grant    6T  PF         1.0          9.450327
14333  Mookie Blaylock     3  PG        18.0          8.942082
14164   Scottie Pippen     4  SF         4.0          5.943970
14141    Shawn Bradley  -1.0   C         0.0          4.486029
14277   David Robinson    -1   C         0.0          3.935965
14269    Dennis Rodman    -1  PF         0.0          3.878018

---------------------------------------------------------------------
Selected Features Top  10  Test year :  1998
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 1.1001175021477503
R-squared (XGBoost): 0.8232519462661078

           Player_name Rank Pos  Points_won  Predicted_points
13894  Dikembe Mutombo    1   C        39.0         56.437317
13764      Gary Payton    2  PG        37.0         25.406759
13836   Michael Jordan    4  SG         6.0          9.586807
13605   David Robinson    3   C        10.0          5.360355
13613     Horace Grant  11T   C         1.0          4.772857
13956   Charles Oakley   -1  PF         0.0          4.403203
13637    Dennis Rodman   5T  PF         4.0          3.712411
13666    Brevin Knight  11T  PG         1.0          2.593031
13601    Kevin Garnett  11T  PF         1.0          2.472509
13815  Mookie Blaylock   5T  PG         4.0          2.433785

---------------------------------------------------------------------
Selected Features Top  10  Test year :  1999
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 8.162537991646758
R-squared (XGBoost): 0.5194406668012073

           Player_name Rank Pos  Points_won  Predicted_points
13269  Alonzo Mourning    1   C        89.0         28.270218
13039  Hakeem Olajuwon   7T   C         1.0         11.273853
13380  Mookie Blaylock   -1  PG         0.0          7.246218
13424      Gary Payton    3  PG         6.0          7.126326
13182  Dikembe Mutombo    2   C        10.0          6.250851
13434   David Robinson    4   C         3.0          3.432545
13237      Eddie Jones   7T  SF         1.0          2.604107
13488       Tim Duncan   5T  PF         2.0          2.332615
13397   Scottie Pippen   7T  SF         1.0          1.582412
13445    Kevin Garnett   7T  PF         1.0          0.998847

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2000
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 2.149285290344258
R-squared (XGBoost): 0.7783321923271005

             Player_name Rank Pos  Points_won  Predicted_points
12956    Alonzo Mourning    1   C        62.0         57.021801
12909    Dikembe Mutombo   3T   C        11.0         26.250931
12708        Gary Payton   5T  PG         4.0         25.422798
12725   Shaquille O'Neal    2   C        21.0         11.290078
12841      Kevin Garnett    7  PF         2.0          8.642687
12987     David Robinson   -1   C         0.0          4.993495
12830         Tim Duncan   -1  PF         0.0          4.258577
12733          Bo Outlaw   8T  PF         1.0          3.521183
12989  Clifford Robinson   8T  SF         1.0          3.465199
12827     Scottie Pippen   8T  SF         1.0          3.026187

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2001
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 9.544107918991092
R-squared (XGBoost): 0.16568382636561607

            Player_name Rank Pos  Points_won  Predicted_points
12427       Gary Payton   -1  PG         0.0         14.628414
12106    David Robinson   5T   C         6.0          7.246685
12510   Dikembe Mutombo    1   C        48.0          7.226408
12492       Kobe Bryant  11T  SG         1.0          6.229113
12403  Shaquille O'Neal   8T   C         2.0          4.663620
12512   Dikembe Mutombo    1   C        48.0          4.644737
12156        Jason Kidd  11T  PG         1.0          3.691214
12514     Allen Iverson  11T  SG         1.0          3.516451
12460     Kevin Garnett    2  PF        26.0          2.334450
12383         Bo Outlaw   -1  PF         0.0          2.227681

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2002
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.455143837680948
R-squared (XGBoost): 0.7391241721116784

           Player_name  Rank Pos  Points_won  Predicted_points
11941      Ben Wallace     1   C       116.0         64.609344
12003  Dikembe Mutombo    3T   C         1.0         19.867197
11852       Tim Duncan    -1  PF         0.0         17.104879
11741       Jason Kidd    -1  PG         0.0          9.474566
12005      Kobe Bryant    3T  SG         1.0          7.371114
11936    Kevin Garnett     2  PF         2.0          5.081962
11950      Gary Payton    -1  PG         0.0          3.649733
11800    Doug Christie  -1.0  SG         0.0          3.448385
11862   David Robinson    -1   C         0.0          3.417320
12041      Eddie Jones    -1  SG         0.0          3.328863

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2003
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 616.9187565260999
R-squared (XGBoost): 0.13761895484073838

             Player_name  Rank Pos  Points_won  Predicted_points
11137        Ben Wallace     1   C       531.0         43.168304
11559         Jason Kidd    -1  PG         0.0         12.616027
11405         Tim Duncan     4  PF        90.0          9.156397
11494   Shaquille O'Neal   13T   C         3.0          6.087445
11505      Dirk Nowitzki  -1.0  PF         0.0          5.039296
11347      Doug Christie   5.0  SG        85.0          4.371146
11231      Tracy McGrady  -1.0  SG         0.0          3.456106
11514  Metta World Peace     2  SF       122.0          2.759891
11412       Shawn Marion   13T  SF         3.0          2.671837
11277       Horace Grant    -1  PF         0.0          2.599921

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2004
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 993.0221413530418
R-squared (XGBoost): -0.4365838462782863

             Player_name Rank Pos  Points_won  Predicted_points
10663        Ben Wallace    2   C       325.0        529.814575
11127      Kevin Garnett    6  PF        36.0        515.175781
10818         Tim Duncan    7  PF         8.0         50.135494
11110        James Posey  10T  SG         1.0         15.865726
10990         Jason Kidd   -1  PG         0.0         15.678362
10650       Theo Ratliff    3   C        90.0         11.880589
10722  Metta World Peace    1  SF       476.0         10.191623
10721        Gary Payton   -1  PG         0.0          8.184460
10675      Kenyon Martin    9  PF         2.0          7.934951
10664       Theo Ratliff    3   C        90.0          7.146442

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2005
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 417.13165937895593
R-squared (XGBoost): -0.0006577998942765007

             Player_name  Rank Pos  Points_won  Predicted_points
10261  Metta World Peace    -1  SF         0.0         86.695534
10427       Vince Carter  -1.0  SG         0.0         45.754253
10343      Kevin Garnett     9  PF        30.0         30.994732
10202        Eddie Jones    -1  SF         0.0         16.259571
10338       Shawn Marion     5  PF        57.0         14.583413
10594      Shane Battier   21T  SG         1.0         14.452746
10455        Ben Wallace     1   C       339.0          9.608687
10592   Andrei Kirilenko    10  PF        25.0          9.399241
10337      Allen Iverson    11  PG        10.0          9.331876
10132       Larry Hughes   6.0  SG        53.0          8.664258

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2006
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 222.47618684465647
R-squared (XGBoost): 0.6191760797514464

             Player_name Rank Pos  Points_won  Predicted_points
9841         Ben Wallace    1   C       420.0        315.705872
9704        Marcus Camby    5   C        55.0        121.235725
9691    Andrei Kirilenko    3  SF       121.0         58.007656
9880         Eddie Jones  13T  SG         1.0         25.008026
9610         Bruce Bowen    2  SF       308.0         14.731955
9730   Metta World Peace    4  SF        65.0         14.613118
10044         Tim Duncan    6  PF        42.0         12.390275
9863        Shawn Marion    7  PF        33.0         11.754384
9745     Alonzo Mourning    8   C        29.0         11.339344
9731   Metta World Peace    4  SF        65.0         11.159016

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2007
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 555.0918089672207
R-squared (XGBoost): -0.0006759055062806052

            Player_name  Rank Pos  Points_won  Predicted_points
9414        Ben Wallace     6   C        42.0        259.742767
9194         Josh Smith   21T  SF         3.0         64.783325
9407       Marcus Camby     1   C       431.0         50.448490
9253    Rasheed Wallace    -1   C         0.0         41.385387
9500    Jermaine O'Neal  10.0   C        11.0         35.907143
9438         Tim Duncan     3   C       158.0         35.237286
9418       Shawn Marion     4  SF        93.0         32.754410
9262         Jason Kidd    -1  PG         0.0         28.555683
9355      Shane Battier     5  SF        86.0         27.954231
9566  Metta World Peace     8  SF        20.0         27.866377

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2008
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 180.41312906350552
R-squared (XGBoost): 0.6973673149607993

          Player_name  Rank Pos  Points_won  Predicted_points
8731    Kevin Garnett     1  PF       493.0        238.733627
8762     Marcus Camby     2   C       178.0        157.407455
8784      Bruce Bowen     4  SF        80.0         75.164268
8630       Josh Smith     6  PF        34.0         70.136452
8949  Rasheed Wallace    12   C         9.0         30.670456
8722    Shane Battier     3  SF       175.0         20.756910
9050    Dwight Howard    7T   C        24.0         18.724415
8898     Caron Butler    -1  SF         0.0         13.999543
8926      Joe Johnson  -1.0  SG         0.0         12.811910
8573       Tim Duncan     9   C        22.0         12.016377

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2009
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 75.30144043996152
R-squared (XGBoost): 0.884226011796919

            Player_name Rank Pos  Points_won  Predicted_points
8212      Dwight Howard    1   C       542.0        409.335541
8484       LeBron James    2  SF       148.0         86.676010
8365      Kevin Garnett    8  PF        31.0         74.446114
8558         Jason Kidd   -1  PG         0.0         23.397129
8556         Chris Paul    6  PG        49.0         23.385948
8426        Kobe Bryant    7  SG        43.0         21.100496
8320     Andre Iguodala  13T  SF         3.0         17.661745
8193   Chauncey Billups   -1  PG         0.0         15.692367
8442  Metta World Peace    5  SF        54.0         14.860799
8254     Gerald Wallace   -1  SF         0.0         13.906159

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2010
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 99.38424982722785
R-squared (XGBoost): 0.8625542503659762

            Player_name  Rank Pos  Points_won  Predicted_points
8018      Dwight Howard     1   C       576.0        455.212372
8041       LeBron James     4  SF        61.0         78.376770
7939      Kevin Garnett    -1  PF         0.0         63.993908
7683         Tim Duncan    14   C         7.0         53.906651
8027         Al Horford  -1.0   C         0.0         52.109390
7544        Dwyane Wade   10T  SG        13.0         42.788338
8050  Metta World Peace     6  SF        29.0         31.550056
7564        Kobe Bryant    12  SG         9.0         25.421659
7553         Josh Smith     2  PF       136.0         23.779091
8016        Rajon Rondo     5  PG        55.0         23.746651

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2011
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 88.16716035016883
R-squared (XGBoost): 0.8675750519952519

        Player_name  Rank Pos  Points_won  Predicted_points
7366  Dwight Howard     1   C       585.0        500.485687
7508     Josh Smith    25  PF         1.0        103.314911
7171  Shane Battier    -1  SF         0.0         98.132858
7270   Shawn Marion    -1  SF         0.0         87.404274
7400      Luol Deng  10.0  SF        24.0         55.859806
7321    Rajon Rondo     5  PG        45.0         41.852245
7288    Dwyane Wade    16  SG         8.0         37.462975
7523   Andrew Bogut   6.0   C        32.0         35.697865
7170  Shane Battier    -1  SF         0.0         31.379112
7186   LeBron James     9  SF        25.0         27.478968

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2012
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 371.46891460799765
R-squared (XGBoost): 0.1791644859007221

            Player_name  Rank Pos  Points_won  Predicted_points
6527        Serge Ibaka   2.0  PF       294.0         71.939651
6747         Josh Smith    10  PF         9.0         45.058495
6987      Kevin Garnett     5   C        44.0         28.764055
6487        Elton Brand    -1   C         0.0         26.800739
6523     Andre Iguodala     7  SF        33.0         24.948992
6916         Tim Duncan    -1   C         0.0         20.987915
6741        Joakim Noah  11.0   C         6.0         18.116911
6877  Russell Westbrook   18T  PG         1.0         17.528141
6938         Marc Gasol   12T   C         5.0         15.632862
6572       LeBron James     4  SF       112.0         14.033783

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2013
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 166.76855302025487
R-squared (XGBoost): 0.3067959152434463

         Player_name Rank Pos  Points_won  Predicted_points
6217      Marc Gasol    1   C       212.0        308.580750
6315      Josh Smith   -1  PF         0.0        129.674530
5996   Dwight Howard   14   C         9.0        125.241989
6265   Kevin Garnett   -1   C         0.0        100.189850
6084    LeBron James    2  PF       149.0         85.931244
6005     Serge Ibaka  3.0  PF       122.0         79.091225
6355  Tyson Chandler   13   C        11.0         75.050079
6330     Joakim Noah  4.0   C       107.0         53.231331
6373      Tony Allen  5.0  SG       102.0         38.298210
6119     Dwyane Wade   16  SG         4.0         35.968391

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2014
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 131.12804491470084
R-squared (XGBoost): 0.8002816152480253

         Player_name Rank Pos  Points_won  Predicted_points
5847     Joakim Noah  1.0   C       555.0        389.650543
5624   Anthony Davis   8T  PF        25.0         73.560791
5514      Tim Duncan  13T   C         5.0         63.002823
5641      Chris Paul  13T  PG         5.0         47.838688
5952     Paul George  7.0  SF        30.0         47.215801
5804     Serge Ibaka  4.0  PF        79.0         37.254623
5754   Dwight Howard   8T   C        25.0         33.367893
5805  Andre Iguodala    5  SF        47.0         30.574993
5895    Jimmy Butler   -1  SG         0.0         26.787954
5616    LeBron James    6  PF        31.0         25.887594

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2015
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 286.18882305480025
R-squared (XGBoost): 0.43616671209994806

         Player_name  Rank Pos  Points_won  Predicted_points
5314   Kawhi Leonard     1  SF       333.0        182.032166
4890      Marc Gasol   10T   C         7.0        119.445473
5304  Tyson Chandler    -1   C         0.0         75.015526
5107  Draymond Green     2  PF       317.0         59.873821
4860    Trevor Ariza   13T  SF         3.0         50.704563
5011  DeAndre Jordan   3.0   C       261.0         49.234047
5078     Joakim Noah  12.0   C         4.0         43.224262
5393   Anthony Davis     4  PF       107.0         34.186897
5227  Andre Iguodala    -1  SF         0.0         30.429501
4915      Tim Duncan     8   C        12.0         24.344286

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2016
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 719.5265886349761
R-squared (XGBoost): 0.2152489891864261

           Player_name  Rank Pos  Points_won  Predicted_points
4570  Hassan Whiteside     3   C        83.0        172.702698
4474    DeAndre Jordan   4.0   C        50.0        118.539948
4426     Kawhi Leonard     1  SF       547.0         98.350952
4524      LeBron James   11T  SF         2.0         48.393795
4362        Chris Paul   13T  PG         1.0         25.265181
4782        Tim Duncan    -1   C         0.0         21.132511
4597    Draymond Green     2  PF       421.0         20.315763
4373       Rudy Gobert   7.0   C        13.0         19.832169
4411       Serge Ibaka  -1.0  PF         0.0         16.793766
4758     Anthony Davis     9   C         4.0         15.848027

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2017
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 204.51557281234597
R-squared (XGBoost): 0.6208938112955023

            Player_name  Rank Pos  Points_won  Predicted_points
3989     Draymond Green     1  PF       434.0        286.679901
4268      Kawhi Leonard     3  SF       182.0        161.258698
4129      Anthony Davis    -1   C         0.0         99.737183
3870   Hassan Whiteside    5T   C         3.0         78.361443
4054      Dwight Howard    -1   C         0.0         69.117729
3951         Marc Gasol    -1   C         0.0         57.324593
4154     DeAndre Jordan  -1.0   C         0.0         37.976128
4051       Trevor Ariza    -1  SF         0.0         24.903065
3977        Rudy Gobert   2.0   C       269.0         21.802750
3988  Russell Westbrook    -1  PG         0.0         14.944891

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2018
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 365.5659120124991
R-squared (XGBoost): 0.16601429384359612

             Player_name  Rank Pos  Points_won  Predicted_points
3177       Anthony Davis     3  PF       139.0         85.507271
3312       Dwight Howard    -1   C         0.0         75.527306
3403         Rudy Gobert   1.0   C       466.0         41.078136
3270      Draymond Green     6  PF        20.0         37.600510
3595         Ben Simmons  -1.0  PG         0.0         19.158146
3276          Al Horford     5   C        37.0         17.170433
3407   LaMarcus Aldridge    -1   C         0.0         12.373671
3180        LeBron James    -1  PF         0.0         11.847625
3350  Karl-Anthony Towns  -1.0   C         0.0         11.324701
3598      Victor Oladipo   15T  SG         1.0         10.675097

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2019
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 325.48472535249516
R-squared (XGBoost): 0.24881567448636666

           Player_name  Rank Pos  Points_won  Predicted_points
2825       Rudy Gobert   1.0   C       411.0         98.663025
2671     Anthony Davis    -1   C         0.0         63.110790
2980        Marc Gasol    -1   C         0.0         53.169937
2876    Draymond Green    6T  PF         6.0         50.017689
2633       Serge Ibaka  -1.0   C         0.0         45.001347
2979        Marc Gasol    -1   C         0.0         44.550789
2562      Myles Turner   5.0   C        15.0         42.642010
3148    Andre Drummond    -1   C         0.0         41.210915
3120  Hassan Whiteside    -1   C         0.0         38.333702
2932       Paul George   3.0  SF       150.0         28.385237

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2020
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 194.18365651781053
R-squared (XGBoost): 0.561505026136258

                Player_name  Rank Pos  Points_won  Predicted_points
2127  Giannis Antetokounmpo   1.0  PF       432.0        155.483047
2270          Anthony Davis     2  PF       200.0         67.744141
2524            Rudy Gobert   3.0   C       187.0         56.406036
2017       Hassan Whiteside    11   C         3.0         39.008465
1968           James Harden  -1.0  SG         0.0         23.418493
2094            Brook Lopez  10.0   C         4.0         22.901798
2259           LeBron James    -1  PG         0.0         18.554605
2198          Kawhi Leonard    8T  SF         5.0          7.452223
2196           Marcus Smart    6T  SG         7.0          6.089771
2206            Ben Simmons   4.0  PG        32.0          4.333143

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2021
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 169.59870745400895
R-squared (XGBoost): 0.6501299504544227

                Player_name  Rank Pos  Points_won  Predicted_points
1379            Rudy Gobert   1.0   C       464.0        332.771637
1895  Giannis Antetokounmpo   5.0  PF        12.0         78.629761
1719           Myles Turner   9.0   C         3.0         44.457592
1422         Draymond Green     3  PF        76.0         30.499010
1423           Jaylen Brown  -1.0  SG         0.0          7.877213
1346             Chris Paul    -1  PG         0.0          7.800599
1937           Jakob Poeltl  -1.0   C         0.0          7.101120
1785            Ben Simmons   2.0  PG       287.0          5.589151
1601            Luka Dončić  -1.0  PG         0.0          4.873163
1698           Jrue Holiday     8  PG         6.0          4.249074

---------------------------------------------------------------------
Selected Features Top  10  Test year :  2022
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 197.57180200311709
R-squared (XGBoost): 0.08198183990156027

                Player_name  Rank Pos  Points_won  Predicted_points
1022            Rudy Gobert   3.0   C       136.0        257.901062
1111  Giannis Antetokounmpo   6.0  PF        58.0        133.214859
1054         Andrew Wiggins  -1.0  SF         0.0        131.693115
1302    Dorian Finney-Smith  -1.0  PF         0.0        130.493576
713            Marcus Smart     1  PG       257.0        108.085640
997       Jaren Jackson Jr.   5.0  PF        99.0         31.949778
657            Bobby Portis  -1.0   C         0.0         30.795650
678              Chris Paul    -1  PG         0.0         27.528786
724            Jordan Poole  -1.0  SG         0.0         21.589699
1026           Myles Turner  -1.0   C         0.0         10.756268

---------------------------------------------------------------------

,Rank_1994,Rank_1995,Rank_1996,Rank_1997,Rank_1998,Rank_1999,Rank_2000,Rank_2001,Rank_2002,Rank_2003,...,Rank_2013,Rank_2014,Rank_2015,Rank_2016,Rank_2017,Rank_2018,Rank_2019,Rank_2020,Rank_2021,Rank_2022
0,1,1,3,2,1,1,1,-1,1,1,...,1,1.0,1,3,1,3,1.0,1.0,1.0,3.0
1,2,4,4,5,2,7T,3T,5T,3T,-1,...,-1,8T,10T,4.0,3,-1,-1,2,5.0,6.0
2,4,2,6,-1,4,-1,5T,1,-1,4,...,14,13T,-1,1,-1,1.0,-1,3.0,9.0,-1.0
3,7T,3,2,1,3,3,2,11T,-1,13T,...,-1,13T,2,11T,5T,6,6T,11,3,-1.0
4,3,5,7,6T,11T,2,7,8T,3T,-1.0,...,2,7.0,13T,13T,-1,-1.0,-1.0,-1.0,-1.0,1
5,-1,6T,5,3,-1,4,-1,1,2,5.0,...,3.0,4.0,3.0,-1,-1,5,-1,10.0,-1,5.0
6,10,-1,-1,4,5T,7T,-1,11T,-1,-1.0,...,13,8T,12.0,2,-1.0,-1,5.0,-1,-1.0,-1.0
7,9,-1,1,-1.0,11T,5T,8T,11T,-1.0,2,...,4.0,5,4,7.0,-1,-1,-1,8T,2.0,-1
8,-1,6T,8T,-1,11T,7T,8T,2,-1,13T,...,5.0,-1,-1,-1.0,2.0,-1.0,-1,6T,-1.0,-1.0
9,7T,-1,-1.0,-1,5T,7T,8T,-1,-1,-1,...,16,6,8,9,-1,15T,3.0,4.0,8,-1.0

In [15]:
top = top_20

rank_data_20 = pd.DataFrame()

for year in range(1994,2024):
    print("Selected Features Top ",20," Test year : ", year)
    Test_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] == year]
    Train_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] < year]
    
    X_train, y_train = Data_Organizer(Train_Data,top)
    X_test , y_test = Data_Organizer(Test_Data,top)
    
    # Initialize and train a XGBoost Regressor model
    xgb_model = XGBRegressor(n_estimators=200,max_depth = 5, random_state=42, n_jobs=-1)
    xgb_model.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred_xgb = xgb_model.predict(X_test)
    
    # Evaluate the model
    mse_xgb = mean_squared_error(y_test, y_pred_xgb)
    r2_xgb = r2_score(y_test, y_pred_xgb)
    
    # Mean Squared Error (MAE)
    print(f'Mean Squared Error (XGBoost): {mse_xgb}')
    print(f'R-squared (XGBoost): {r2_xgb}')
    
    Test_Data_copy = Test_Data.copy()
    Test_Data_copy.loc[:, 'Predicted_points'] = y_pred_xgb
    
    # Select only the desired columns
    Test_Data_concatenated = Test_Data_copy[['Player_name','Rank','Pos','Points_won', 'Predicted_points']]
    
    # Display the concatenated DataFrame sorted by 'Points_won'
    display(Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10))

    Test_Data_concatenated = Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10)
    
    if rank_data_20.empty:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_20 = pd.DataFrame(new_rank_column)
    else:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_20 = pd.concat([rank_data_20.reset_index(drop=True), new_rank_column.reset_index(drop=True)], axis=1)

    print("---------------------------------------------------------------------")

display(rank_data_20)

Selected Features Top  20  Test year :  1994
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.086077217081475
R-squared (XGBoost): -0.9183968027655238

           Player_name Rank Pos  Points_won  Predicted_points
15651  Hakeem Olajuwon    1   C        23.0         72.997940
15539   David Robinson    2   C        22.0          9.000013
15477   Scottie Pippen    4  SF        11.0          8.998991
15583  Mookie Blaylock   7T  PG         3.0          8.998991
15743  Dikembe Mutombo    3   C        19.0          1.227015
15796      Dan Majerle   -1  SG         0.0          1.226771
15540     Horace Grant   10  PF         1.0          1.226771
15649   Charles Oakley    9  PF         2.0          1.000326
15739    Patrick Ewing   -1   C         0.0          1.000284
15677    Nate McMillan   7T  PG         3.0          1.000082

---------------------------------------------------------------------
Selected Features Top  20  Test year :  1995
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 1.9940115088525399
R-squared (XGBoost): 0.6830644345319289

           Player_name Rank Pos  Points_won  Predicted_points
15113   David Robinson    4   C        12.0         20.173628
15026  Dikembe Mutombo    1   C        45.0         19.081179
15199   Scottie Pippen    2  SF        16.0         15.400890
14994  Hakeem Olajuwon    3   C        13.0         12.852371
15121    Dennis Rodman    5  PF        11.0          7.233636
15249    Nate McMillan   6T  PG         2.0          6.874817
15151      Gary Payton   6T  PG         2.0          5.864574
15077  Mookie Blaylock   -1  PG         0.0          4.718950
15051    Patrick Ewing   -1   C         0.0          4.657837
15045   Charles Oakley   -1  PF         0.0          2.943335

---------------------------------------------------------------------
Selected Features Top  20  Test year :  1996
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 8.455872463731984
R-squared (XGBoost): -0.12702327502698085

           Player_name  Rank Pos  Points_won  Predicted_points
14887  Dikembe Mutombo     3   C        11.0         46.879585
14619   Michael Jordan     6  SG         7.0         15.659716
14897   David Robinson     4   C         9.0         15.245380
14839    Shawn Bradley  -1.0   C         0.0         15.205432
14749   Scottie Pippen     2  SF        15.0         13.398292
14797  Hakeem Olajuwon     5   C         8.0         10.322568
14909    Dennis Rodman     7  PF         4.0          8.213308
14555     Horace Grant    8T  PF         1.0          7.751288
14844      Gary Payton     1  PG        56.0          7.125830
14838   Charles Oakley    -1  PF         0.0          5.673335

---------------------------------------------------------------------
Selected Features Top  20  Test year :  1997
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 5.050996663597681
R-squared (XGBoost): 0.43312285859147737

           Player_name  Rank Pos  Points_won  Predicted_points
14149      Gary Payton     2  PG        25.0         42.483868
14489  Dikembe Mutombo     1   C        60.0         18.018785
14210  Hakeem Olajuwon    -1   C         0.0         17.645149
14333  Mookie Blaylock     3  PG        18.0         12.127672
14279     Horace Grant    6T  PF         1.0          8.687144
14081   Michael Jordan     5  SG         3.0          8.662812
14164   Scottie Pippen     4  SF         4.0          5.556717
14269    Dennis Rodman    -1  PF         0.0          5.182480
14141    Shawn Bradley  -1.0   C         0.0          5.049559
14189   Charles Oakley    -1  PF         0.0          3.169557

---------------------------------------------------------------------
Selected Features Top  20  Test year :  1998
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 0.6802639385798496
R-squared (XGBoost): 0.8907068318296855

           Player_name Rank Pos  Points_won  Predicted_points
13894  Dikembe Mutombo    1   C        39.0         49.794662
13764      Gary Payton    2  PG        37.0         25.002893
13836   Michael Jordan    4  SG         6.0          4.238340
13605   David Robinson    3   C        10.0          3.872688
13637    Dennis Rodman   5T  PF         4.0          2.540909
13815  Mookie Blaylock   5T  PG         4.0          2.058673
13666    Brevin Knight  11T  PG         1.0          1.870877
13601    Kevin Garnett  11T  PF         1.0          1.149413
13744        Bo Outlaw   5T  PF         4.0          0.990155
13613     Horace Grant  11T   C         1.0          0.915808

---------------------------------------------------------------------
Selected Features Top  20  Test year :  1999
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 16.048649105479956
R-squared (XGBoost): 0.05515562429683496

           Player_name Rank Pos  Points_won  Predicted_points
13380  Mookie Blaylock   -1  PG         0.0          4.691400
13434   David Robinson    4   C         3.0          3.044982
13269  Alonzo Mourning    1   C        89.0          2.588280
13237      Eddie Jones   7T  SF         1.0          2.510542
13424      Gary Payton    3  PG         6.0          2.425686
13488       Tim Duncan   5T  PF         2.0          1.492062
13397   Scottie Pippen   7T  SF         1.0          1.262931
13445    Kevin Garnett   7T  PF         1.0          0.762325
13244      Eddie Jones   7T  SG         1.0          0.472051
13048         Rick Fox   -1  SF         0.0          0.461132

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2000
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 5.436769813411308
R-squared (XGBoost): 0.4392755346275832

             Player_name Rank Pos  Points_won  Predicted_points
12909    Dikembe Mutombo   3T   C        11.0         35.460213
12956    Alonzo Mourning    1   C        62.0         30.364283
12708        Gary Payton   5T  PG         4.0         30.188181
12725   Shaquille O'Neal    2   C        21.0         10.752117
12987     David Robinson   -1   C         0.0          8.091877
12841      Kevin Garnett    7  PF         2.0          3.734881
12741        Eddie Jones   3T  SG        11.0          3.596859
12989  Clifford Robinson   8T  SF         1.0          3.285701
12827     Scottie Pippen   8T  SF         1.0          2.774099
12830         Tim Duncan   -1  PF         0.0          2.765886

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2001
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 8.854909548860407
R-squared (XGBoost): 0.2259314002534092

            Player_name Rank Pos  Points_won  Predicted_points
12427       Gary Payton   -1  PG         0.0         12.942578
12510   Dikembe Mutombo    1   C        48.0          7.367206
12106    David Robinson   5T   C         6.0          7.310078
12271        Tim Duncan    3  PF        14.0          6.093108
12512   Dikembe Mutombo    1   C        48.0          5.466846
12403  Shaquille O'Neal   8T   C         2.0          4.313796
12492       Kobe Bryant  11T  SG         1.0          4.062893
12514     Allen Iverson  11T  SG         1.0          3.993841
12285     Doug Christie  4.0  SG         9.0          3.297477
12460     Kevin Garnett    2  PF        26.0          3.002495

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2002
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 5.8372479355044256
R-squared (XGBoost): 0.7957387649494627

            Player_name Rank Pos  Points_won  Predicted_points
11941       Ben Wallace    1   C       116.0         70.866142
12003   Dikembe Mutombo   3T   C         1.0         15.919772
11936     Kevin Garnett    2  PF         2.0         12.617213
11852        Tim Duncan   -1  PF         0.0         12.160277
12005       Kobe Bryant   3T  SG         1.0          8.008398
11950       Gary Payton   -1  PG         0.0          7.235162
11741        Jason Kidd   -1  PG         0.0          5.626543
11927  Shaquille O'Neal   -1   C         0.0          5.576597
12041       Eddie Jones   -1  SG         0.0          5.114178
12035   Alonzo Mourning   -1   C         0.0          4.033085

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2003
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 612.5018186899268
R-squared (XGBoost): 0.1437933229034174

         Player_name  Rank Pos  Points_won  Predicted_points
11137    Ben Wallace     1   C       531.0         43.991444
11176    Gary Payton    11  PG         5.0         14.952084
11405     Tim Duncan     4  PF        90.0         14.319723
11559     Jason Kidd    -1  PG         0.0         12.680809
11347  Doug Christie   5.0  SG        85.0          5.587960
11505  Dirk Nowitzki  -1.0  PF         0.0          5.486066
11183  Kevin Garnett     3  PF       121.0          3.514585
11412   Shawn Marion   13T  SF         3.0          3.066195
11231  Tracy McGrady  -1.0  SG         0.0          3.006606
11411  Allen Iverson     6  SG        29.0          2.519733

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2004
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 626.8590610806402
R-squared (XGBoost): 0.09313643317701159

             Player_name  Rank Pos  Points_won  Predicted_points
11127      Kevin Garnett     6  PF        36.0        118.228088
10663        Ben Wallace     2   C       325.0         51.096737
10776        Jeff Foster  -1.0   C         0.0         31.655577
10721        Gary Payton    -1  PG         0.0         14.054321
10818         Tim Duncan     7  PF         8.0          8.821309
10871   Andrei Kirilenko     5  PF        67.0          8.800423
10722  Metta World Peace     1  SF       476.0          8.481586
11110        James Posey   10T  SG         1.0          7.967699
10650       Theo Ratliff     3   C        90.0          7.196680
10898       Marcus Camby  -1.0   C         0.0          6.725851

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2005
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 450.2833823441589
R-squared (XGBoost): -0.08018552074494201

             Player_name  Rank Pos  Points_won  Predicted_points
10261  Metta World Peace    -1  SF         0.0        155.818680
10343      Kevin Garnett     9  PF        30.0         29.829981
10151      Manu Ginóbili   18T  SG         2.0         14.376117
10592   Andrei Kirilenko    10  PF        25.0         13.923719
10515    Tayshaun Prince     7  SF        46.0         12.901889
10390   Richard Hamilton  -1.0  SG         0.0          9.523564
10437      Jason Collins  -1.0   C         0.0          7.875559
10338       Shawn Marion     5  PF        57.0          7.366748
10398       Marcus Camby     3   C       168.0          6.835884
10352     Tyson Chandler   18T   C         2.0          6.182452

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2006
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 500.3096621365252
R-squared (XGBoost): 0.14359424451077107

            Player_name  Rank Pos  Points_won  Predicted_points
9704       Marcus Camby     5   C        55.0        117.241676
9691   Andrei Kirilenko     3  SF       121.0         94.615013
9863       Shawn Marion     7  PF        33.0         76.929039
9951         Chris Paul  -1.0  PG         0.0         41.021446
9610        Bruce Bowen     2  SF       308.0         24.157465
9841        Ben Wallace     1   C       420.0         22.800316
10028     Kevin Garnett   13T  PF         1.0         20.453394
10044        Tim Duncan     6  PF        42.0         20.453094
10019     Shane Battier   10T  SF         3.0         16.338974
9625    Tayshaun Prince   13T  SF         1.0         13.772455

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2007
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 424.6623868584171
R-squared (XGBoost): 0.23445201020954154

        Player_name  Rank Pos  Points_won  Predicted_points
9414    Ben Wallace     6   C        42.0        145.904541
9339    Bruce Bowen     2  SF       206.0         91.138802
9194     Josh Smith   21T  SF         3.0         61.022392
9407   Marcus Camby     1   C       431.0         44.275051
9418   Shawn Marion     4  SF        93.0         30.097841
9355  Shane Battier     5  SF        86.0         29.875917
9356  Kevin Garnett   13T  PF         7.0         23.308081
9488  Renaldo Major  -1.0  PF         0.0         20.955334
9438     Tim Duncan     3   C       158.0         18.647120
9117    Baron Davis  -1.0  PG         0.0         17.421724

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2008
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 412.4437222700933
R-squared (XGBoost): 0.30814929187207674

            Player_name Rank Pos  Points_won  Predicted_points
8784        Bruce Bowen    4  SF        80.0        136.171280
8731      Kevin Garnett    1  PF       493.0         85.701813
8573         Tim Duncan    9   C        22.0         56.585663
8762       Marcus Camby    2   C       178.0         48.203835
8944      Allen Iverson   -1  SG         0.0         34.565952
8949    Rasheed Wallace   12   C         9.0         29.067163
8630         Josh Smith    6  PF        34.0         25.410015
8568       Shawn Marion   -1  PF         0.0         22.898840
8588       Shawn Marion   -1  PF         0.0         22.771894
8659  Metta World Peace  16T  SF         1.0         18.253746

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2009
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 340.5297247841179
R-squared (XGBoost): 0.47644448619295154

            Player_name  Rank Pos  Points_won  Predicted_points
8365      Kevin Garnett     8  PF        31.0        337.924683
8212      Dwight Howard     1   C       542.0        326.862701
8274    Tayshaun Prince    -1  SF         0.0        104.579529
8484       LeBron James     2  SF       148.0         58.759449
8442  Metta World Peace     5  SF        54.0         32.815224
8426        Kobe Bryant     7  SG        43.0         29.598295
8558         Jason Kidd    -1  PG         0.0         27.966606
8254     Gerald Wallace    -1  SF         0.0         21.341003
8556         Chris Paul     6  PG        49.0         19.878376
8430          Pau Gasol  -1.0   C         0.0         14.626678

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2010
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 203.8172923130651
R-squared (XGBoost): 0.7181261560152024

            Player_name Rank Pos  Points_won  Predicted_points
8018      Dwight Howard    1   C       576.0        330.729309
7905          Raja Bell   -1  SG         0.0         86.681824
7911          Raja Bell   -1  SG         0.0         86.424042
8041       LeBron James    4  SF        61.0         51.408932
8050  Metta World Peace    6  SF        29.0         39.697762
8016        Rajon Rondo    5  PG        55.0         37.751644
7683         Tim Duncan   14   C         7.0         24.041027
7544        Dwyane Wade  10T  SG        13.0         22.960293
7553         Josh Smith    2  PF       136.0         19.309572
7564        Kobe Bryant   12  SG         9.0         14.329188

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2011
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 29.500221365944828
R-squared (XGBoost): 0.9556913791371038

            Player_name  Rank Pos  Points_won  Predicted_points
7366      Dwight Howard     1   C       585.0        558.207031
7321        Rajon Rondo     5  PG        45.0         99.752144
7121      Kevin Garnett     2  PF        77.0         93.630165
7523       Andrew Bogut   6.0   C        32.0         54.869850
7231         Chris Paul   12T  PG        13.0         50.922077
7428  Metta World Peace    18  SF         6.0         39.652618
7039        Kobe Bryant    11  SG        18.0         30.120306
7400          Luol Deng  10.0  SF        24.0         25.476860
7508         Josh Smith    25  PF         1.0         22.463537
7391     Tyson Chandler     3   C        70.0         15.104370

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2012
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 367.499217194185
R-squared (XGBoost): 0.18793633325953552

         Player_name  Rank Pos  Points_won  Predicted_points
6510   Dwight Howard     3   C       186.0         64.167885
6779     Dwyane Wade   18T  SG         1.0         40.747799
6527     Serge Ibaka   2.0  PF       294.0         40.739082
6938      Marc Gasol   12T   C         5.0         33.647858
6987   Kevin Garnett     5   C        44.0         28.987278
6484     Rajon Rondo    -1  PG         0.0         26.234222
6747      Josh Smith    10  PF         9.0         24.066351
6523  Andre Iguodala     7  SF        33.0         23.565990
6487     Elton Brand    -1   C         0.0         23.107344
6795   Greg Stiemsma  -1.0   C         0.0         22.629318

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2013
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 99.74917447453335
R-squared (XGBoost): 0.5853742570492743

         Player_name Rank Pos  Points_won  Predicted_points
6217      Marc Gasol    1   C       212.0        261.224609
6005     Serge Ibaka  3.0  PF       122.0        203.515930
6094     Mike Conley   21  PG         1.0        109.185081
6355  Tyson Chandler   13   C        11.0         71.068802
6242     Paul George  8.0  SF        57.0         65.428741
6419      Tim Duncan    6   C        94.0         55.940765
6084    LeBron James    2  PF       149.0         52.696842
6373      Tony Allen  5.0  SG       102.0         43.336460
6206   Larry Sanders  7.0   C        90.0         41.631802
6265   Kevin Garnett   -1   C         0.0         34.917080

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2014
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 314.5666643304646
R-squared (XGBoost): 0.5208900877172029

         Player_name  Rank Pos  Points_won  Predicted_points
5847     Joakim Noah   1.0   C       555.0        185.015472
5804     Serge Ibaka   4.0  PF        79.0        135.840561
5641      Chris Paul   13T  PG         5.0         48.324287
5952     Paul George   7.0  SF        30.0         42.166485
5805  Andre Iguodala     5  SF        47.0         35.439014
5898  DeAndre Jordan   3.0   C       121.0         34.505039
5895    Jimmy Butler    -1  SG         0.0         32.403660
5948     Roy Hibbert   2.0   C       166.0         30.014498
5610    Kevin Durant  -1.0  SF         0.0         28.130236
5514      Tim Duncan   13T   C         5.0         18.587173

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2015
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 224.8172711954495
R-squared (XGBoost): 0.5570775272010686

         Player_name  Rank Pos  Points_won  Predicted_points
5314   Kawhi Leonard     1  SF       333.0        187.474838
5011  DeAndre Jordan   3.0   C       261.0        112.960121
5393   Anthony Davis     4  PF       107.0         62.814960
5134     Rudy Gobert   5.0   C        33.0         54.326725
5107  Draymond Green     2  PF       317.0         44.597351
5343    LeBron James   13T  SF         3.0         37.463657
5349      Chris Paul   15T  PG         1.0         36.350437
4915      Tim Duncan     8   C        12.0         33.191002
5304  Tyson Chandler    -1   C         0.0         30.660101
5017    Paul Millsap  -1.0  PF         0.0         30.024940

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2016
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 374.83705714362696
R-squared (XGBoost): 0.5911843090581408

           Player_name  Rank Pos  Points_won  Predicted_points
4570  Hassan Whiteside     3   C        83.0        247.672714
4426     Kawhi Leonard     1  SF       547.0        218.235550
4597    Draymond Green     2  PF       421.0        206.136734
4474    DeAndre Jordan   4.0   C        50.0        143.461899
4820    Andre Drummond    10   C         3.0         61.940788
4580       Danny Green  -1.0  SG         0.0         38.558525
4373       Rudy Gobert   7.0   C        13.0         26.317154
4816     Stephen Curry  -1.0  PG         0.0         20.565599
4524      LeBron James   11T  SF         2.0         19.584911
4782        Tim Duncan    -1   C         0.0         19.268309

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2017
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 71.73434557778366
R-squared (XGBoost): 0.8670275618758982

                 Player_name  Rank Pos  Points_won  Predicted_points
3989          Draymond Green     1  PF       434.0        328.858215
3977             Rudy Gobert   2.0   C       269.0        204.125778
4268           Kawhi Leonard     3  SF       182.0         90.200378
4154          DeAndre Jordan  -1.0   C         0.0         66.679642
4129           Anthony Davis    -1   C         0.0         62.198044
3870        Hassan Whiteside    5T   C         3.0         60.429436
4212   Giannis Antetokounmpo  -1.0  SF         0.0         39.491463
4127  Michael Kidd-Gilchrist  -1.0  SF         0.0         15.142174
3837            Andrew Bogut  -1.0   C         0.0         13.956816
4147            LeBron James    5T  SF         3.0         13.837459

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2018
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 261.54399128071793
R-squared (XGBoost): 0.40332524698923244

           Player_name  Rank Pos  Points_won  Predicted_points
3403       Rudy Gobert   1.0   C       466.0        114.393700
3177     Anthony Davis     3  PF       139.0         68.062157
3324    Andre Drummond   15T   C         1.0         24.558109
3337      Andre Ingram  -1.0  SG         0.0         20.656662
3270    Draymond Green     6  PF        20.0         17.165174
3598    Victor Oladipo   15T  SG         1.0         15.139423
3469     Kawhi Leonard    -1  SF         0.0         12.142735
3369       Paul George   4.0  SF        38.0          9.332983
3311  Hassan Whiteside    -1   C         0.0          8.114426
3180      LeBron James    -1  PF         0.0          7.801546

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2019
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 77.95004431194582
R-squared (XGBoost): 0.8200995410865661

                Player_name  Rank Pos  Points_won  Predicted_points
2825            Rudy Gobert   1.0   C       411.0        400.543152
3114  Giannis Antetokounmpo   2.0  PF       280.0        219.949417
2562           Myles Turner   5.0   C        15.0        108.326515
2876         Draymond Green    6T  PF         6.0         82.068649
2738            Brook Lopez  -1.0   C         0.0         61.028759
2702          Kawhi Leonard    6T  SF         6.0         54.203087
2671          Anthony Davis    -1   C         0.0         53.524399
2979             Marc Gasol    -1   C         0.0         50.262630
2980             Marc Gasol    -1   C         0.0         46.374355
3120       Hassan Whiteside    -1   C         0.0         39.541729

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2020
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 172.73777710930847
R-squared (XGBoost): 0.6099329448362725

                Player_name  Rank Pos  Points_won  Predicted_points
2524            Rudy Gobert   3.0   C       187.0        257.562073
2127  Giannis Antetokounmpo   1.0  PF       432.0        232.339020
2017       Hassan Whiteside    11   C         3.0        161.975632
2198          Kawhi Leonard    8T  SF         5.0         90.943665
2270          Anthony Davis     2  PF       200.0         54.024307
2466         Jonathan Isaac  -1.0  PF         0.0         22.985788
2173           Clint Capela  -1.0   C         0.0         21.364456
2094            Brook Lopez  10.0   C         4.0         20.100845
2259           LeBron James    -1  PG         0.0         14.285176
2340            Joel Embiid    -1   C         0.0         14.193429

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2021
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 179.870469350579
R-squared (XGBoost): 0.6289400375262957

                Player_name Rank Pos  Points_won  Predicted_points
1379            Rudy Gobert  1.0   C       464.0        461.632660
1719           Myles Turner  9.0   C         3.0        138.804626
1895  Giannis Antetokounmpo  5.0  PF        12.0        100.947174
1716           Clint Capela  6.0   C        10.0         83.014015
1422         Draymond Green    3  PF        76.0         45.943455
1628         Andre Drummond   -1   C         0.0         23.836163
1517           LeBron James   -1  PG         0.0         14.550562
1399            Joel Embiid    7   C         7.0         10.188264
1741       Matisse Thybulle  11T  SG         1.0         10.074054
1785            Ben Simmons  2.0  PG       287.0          7.368552

---------------------------------------------------------------------
Selected Features Top  20  Test year :  2022
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 172.50584228394226
R-squared (XGBoost): 0.1984509209606854

                Player_name  Rank Pos  Points_won  Predicted_points
1022            Rudy Gobert   3.0   C       136.0        268.504150
1111  Giannis Antetokounmpo   6.0  PF        58.0        110.966522
713            Marcus Smart     1  PG       257.0         56.889580
1123         Draymond Green    10  PF         2.0         48.614552
1007            Joel Embiid    -1   C         0.0         30.578260
1176            Jae Crowder    -1  PF         0.0         28.291428
997       Jaren Jackson Jr.   5.0  PF        99.0         26.658026
1306            Bam Adebayo   4.0   C       128.0         24.433558
1026           Myles Turner  -1.0   C         0.0         19.725767
1159          Herbert Jones  -1.0  PF         0.0         19.420916

---------------------------------------------------------------------

,Rank_1994,Rank_1995,Rank_1996,Rank_1997,Rank_1998,Rank_1999,Rank_2000,Rank_2001,Rank_2002,Rank_2003,...,Rank_2013,Rank_2014,Rank_2015,Rank_2016,Rank_2017,Rank_2018,Rank_2019,Rank_2020,Rank_2021,Rank_2022
0,1,4,3,2,1,-1,3T,-1,1,1,...,1,1.0,1,3,1,1.0,1.0,3.0,1.0,3.0
1,2,1,6,1,2,4,1,1,3T,11,...,3.0,4.0,3.0,1,2.0,3,2.0,1.0,9.0,6.0
2,4,2,4,-1,4,1,5T,5T,2,4,...,21,13T,4,2,3,15T,5.0,11,5.0,1
3,7T,3,-1.0,3,3,7T,2,3,-1,-1,...,13,7.0,5.0,4.0,-1.0,-1.0,6T,8T,6.0,10
4,3,5,2,6T,5T,3,-1,1,3T,5.0,...,8.0,5,2,10,-1,6,-1.0,2,3,-1
5,-1,6T,5,5,5T,5T,7,8T,-1,-1.0,...,6,3.0,13T,-1.0,5T,15T,6T,-1.0,-1,-1
6,10,6T,7,4,11T,7T,3T,11T,-1,3,...,2,-1,15T,7.0,-1.0,-1,-1,-1.0,-1,5.0
7,9,-1,8T,-1,11T,7T,8T,11T,-1,13T,...,5.0,2.0,8,-1.0,-1.0,4.0,-1,10.0,7,4.0
8,-1,-1,1,-1.0,5T,7T,8T,4.0,-1,-1.0,...,7.0,-1.0,-1,11T,-1.0,-1,-1,-1,11T,-1.0
9,7T,-1,-1,-1,11T,-1,-1,2,-1,6,...,-1,13T,-1.0,-1,5T,-1,-1,-1,2.0,-1.0

In [16]:
top = top_30

rank_data_30 = pd.DataFrame()

for year in range(1994,2024):
    print("Selected Features Top ",30," Test year : ", year)
    Test_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] == year]
    Train_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] < year]
    
    X_train, y_train = Data_Organizer(Train_Data,top)
    X_test , y_test = Data_Organizer(Test_Data,top)
    
    # Initialize and train a XGBoost Regressor model
    xgb_model = XGBRegressor(n_estimators=200,max_depth = 5, random_state=42, n_jobs=-1)
    xgb_model.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred_xgb = xgb_model.predict(X_test)
    
    # Evaluate the model
    mse_xgb = mean_squared_error(y_test, y_pred_xgb)
    r2_xgb = r2_score(y_test, y_pred_xgb)
    
    # Mean Squared Error (MAE)
    print(f'Mean Squared Error (XGBoost): {mse_xgb}')
    print(f'R-squared (XGBoost): {r2_xgb}')
    
    Test_Data_copy = Test_Data.copy()
    Test_Data_copy.loc[:, 'Predicted_points'] = y_pred_xgb
    
    # Select only the desired columns
    Test_Data_concatenated = Test_Data_copy[['Player_name','Rank','Pos','Points_won', 'Predicted_points']]
    
    # Display the concatenated DataFrame sorted by 'Points_won'
    display(Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10))

    Test_Data_concatenated = Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10)

    if rank_data_30.empty:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_30 = pd.DataFrame(new_rank_column)
    else:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_30 = pd.concat([rank_data_30.reset_index(drop=True), new_rank_column.reset_index(drop=True)], axis=1)

    print("---------------------------------------------------------------------")

display(rank_data_30)

Selected Features Top  30  Test year :  1994
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.086059603054944
R-squared (XGBoost): -0.9183920341620857

           Player_name Rank Pos  Points_won  Predicted_points
15651  Hakeem Olajuwon    1   C        23.0         72.997879
15539   David Robinson    2   C        22.0          9.000184
15583  Mookie Blaylock   7T  PG         3.0          8.998990
15477   Scottie Pippen    4  SF        11.0          8.998990
15743  Dikembe Mutombo    3   C        19.0          1.226939
15540     Horace Grant   10  PF         1.0          1.226770
15796      Dan Majerle   -1  SG         0.0          1.226770
15649   Charles Oakley    9  PF         2.0          1.000250
15739    Patrick Ewing   -1   C         0.0          1.000208
15784      Gary Payton    5  PG         9.0          1.000081

---------------------------------------------------------------------
Selected Features Top  30  Test year :  1995
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 2.1318432164350565
R-squared (XGBoost): 0.661156953061457

           Player_name Rank Pos  Points_won  Predicted_points
15026  Dikembe Mutombo    1   C        45.0         17.985172
15113   David Robinson    4   C        12.0         15.979774
15199   Scottie Pippen    2  SF        16.0         15.706153
14994  Hakeem Olajuwon    3   C        13.0         14.023102
15151      Gary Payton   6T  PG         2.0         10.172175
15249    Nate McMillan   6T  PG         2.0          6.418117
15121    Dennis Rodman    5  PF        11.0          6.412051
15077  Mookie Blaylock   -1  PG         0.0          4.039550
15045   Charles Oakley   -1  PF         0.0          3.281556
15051    Patrick Ewing   -1   C         0.0          3.216337

---------------------------------------------------------------------
Selected Features Top  30  Test year :  1996
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.3611717095062135
R-squared (XGBoost): 0.01888162532407278

           Player_name  Rank Pos  Points_won  Predicted_points
14887  Dikembe Mutombo     3   C        11.0         47.004784
14619   Michael Jordan     6  SG         7.0         20.146965
14897   David Robinson     4   C         9.0         16.412519
14749   Scottie Pippen     2  SF        15.0         14.689404
14839    Shawn Bradley  -1.0   C         0.0         14.096360
14844      Gary Payton     1  PG        56.0         14.023783
14797  Hakeem Olajuwon     5   C         8.0         10.211756
14909    Dennis Rodman     7  PF         4.0          9.358034
14555     Horace Grant    8T  PF         1.0          7.178227
14838   Charles Oakley    -1  PF         0.0          5.815392

---------------------------------------------------------------------
Selected Features Top  30  Test year :  1997
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 6.666212808999273
R-squared (XGBoost): 0.2518459399466787

           Player_name  Rank Pos  Points_won  Predicted_points
14149      Gary Payton     2  PG        25.0         55.859241
14210  Hakeem Olajuwon    -1   C         0.0         18.539038
14489  Dikembe Mutombo     1   C        60.0         17.242498
14081   Michael Jordan     5  SG         3.0         12.687528
14333  Mookie Blaylock     3  PG        18.0          9.459630
14279     Horace Grant    6T  PF         1.0          8.076218
14164   Scottie Pippen     4  SF         4.0          7.760162
14141    Shawn Bradley  -1.0   C         0.0          4.542079
14269    Dennis Rodman    -1  PF         0.0          3.818520
14277   David Robinson    -1   C         0.0          2.743705

---------------------------------------------------------------------
Selected Features Top  30  Test year :  1998
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 0.5517017540727487
R-squared (XGBoost): 0.9113620035282045

           Player_name Rank Pos  Points_won  Predicted_points
13894  Dikembe Mutombo    1   C        39.0         47.644524
13764      Gary Payton    2  PG        37.0         24.993776
13605   David Robinson    3   C        10.0          5.760185
13836   Michael Jordan    4  SG         6.0          3.895926
13744        Bo Outlaw   5T  PF         4.0          2.581169
13666    Brevin Knight  11T  PG         1.0          2.511089
13842   Scottie Pippen   9T  SF         2.0          2.349890
13815  Mookie Blaylock   5T  PG         4.0          2.072986
13601    Kevin Garnett  11T  PF         1.0          1.411767
13637    Dennis Rodman   5T  PF         4.0          1.376810

---------------------------------------------------------------------
Selected Features Top  30  Test year :  1999
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 15.748217066210627
R-squared (XGBoost): 0.07284318919522448

           Player_name Rank Pos  Points_won  Predicted_points
13434   David Robinson    4   C         3.0          5.102100
13269  Alonzo Mourning    1   C        89.0          3.447570
13488       Tim Duncan   5T  PF         2.0          2.800249
13380  Mookie Blaylock   -1  PG         0.0          2.371383
13445    Kevin Garnett   7T  PF         1.0          2.364936
13237      Eddie Jones   7T  SF         1.0          1.349416
13397   Scottie Pippen   7T  SF         1.0          1.111973
13424      Gary Payton    3  PG         6.0          0.939462
13400    Derrick McKey   -1  SF         0.0          0.693554
13406    Dennis Rodman   -1  PF         0.0          0.640014

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2000
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 4.464500822849083
R-squared (XGBoost): 0.539551071139421

             Player_name Rank Pos  Points_won  Predicted_points
12708        Gary Payton   5T  PG         4.0         36.540047
12956    Alonzo Mourning    1   C        62.0         33.344120
12909    Dikembe Mutombo   3T   C        11.0         17.501236
12725   Shaquille O'Neal    2   C        21.0         15.002444
12987     David Robinson   -1   C         0.0          6.184202
12841      Kevin Garnett    7  PF         2.0          5.689783
12741        Eddie Jones   3T  SG        11.0          4.275136
12830         Tim Duncan   -1  PF         0.0          3.809009
12827     Scottie Pippen   8T  SF         1.0          2.470435
12989  Clifford Robinson   8T  SF         1.0          2.163219

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2001
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 8.736526754402494
R-squared (XGBoost): 0.23628005524920392

            Player_name Rank Pos  Points_won  Predicted_points
12210   Alonzo Mourning   -1   C         0.0         23.630667
12427       Gary Payton   -1  PG         0.0         15.888637
12512   Dikembe Mutombo    1   C        48.0         14.765484
12510   Dikembe Mutombo    1   C        48.0          7.046136
12106    David Robinson   5T   C         6.0          5.318902
12271        Tim Duncan    3  PF        14.0          4.834636
12514     Allen Iverson  11T  SG         1.0          3.993126
12403  Shaquille O'Neal   8T   C         2.0          3.992910
12460     Kevin Garnett    2  PF        26.0          3.872061
12492       Kobe Bryant  11T  SG         1.0          2.526384

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2002
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 14.101559027014968
R-squared (XGBoost): 0.5065479666408549

            Player_name  Rank Pos  Points_won  Predicted_points
11941       Ben Wallace     1   C       116.0         48.837875
12003   Dikembe Mutombo    3T   C         1.0         37.498817
11852        Tim Duncan    -1  PF         0.0         15.330629
11936     Kevin Garnett     2  PF         2.0         14.498513
12035   Alonzo Mourning    -1   C         0.0         13.209860
11950       Gary Payton    -1  PG         0.0          9.256676
12005       Kobe Bryant    3T  SG         1.0          6.397583
11927  Shaquille O'Neal    -1   C         0.0          6.229107
12041       Eddie Jones    -1  SG         0.0          4.529962
11800     Doug Christie  -1.0  SG         0.0          4.069553

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2003
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 625.1127490701584
R-squared (XGBoost): 0.12616470129532287

             Player_name  Rank Pos  Points_won  Predicted_points
11137        Ben Wallace     1   C       531.0         37.820171
11559         Jason Kidd    -1  PG         0.0         12.137918
11405         Tim Duncan     4  PF        90.0         10.825011
11412       Shawn Marion   13T  SF         3.0          8.941925
11505      Dirk Nowitzki  -1.0  PF         0.0          8.029982
11183      Kevin Garnett     3  PF       121.0          5.903355
11463        Kobe Bryant     8  SG        16.0          4.375247
11514  Metta World Peace     2  SF       122.0          3.898347
11347      Doug Christie   5.0  SG        85.0          3.647358
11411      Allen Iverson     6  SG        29.0          3.043087

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2004
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 631.3540304802882
R-squared (XGBoost): 0.08663365729705896

            Player_name  Rank Pos  Points_won  Predicted_points
11127     Kevin Garnett     6  PF        36.0        121.390091
10663       Ben Wallace     2   C       325.0         57.262726
10818        Tim Duncan     7  PF         8.0         16.196669
10717   Jermaine O'Neal  -1.0  PF         0.0          7.950375
10650      Theo Ratliff     3   C        90.0          6.693466
11017   Rasheed Wallace  -1.0  PF         0.0          6.193973
10664      Theo Ratliff     3   C        90.0          5.243327
10764  Shaquille O'Neal   10T   C         1.0          4.845707
10852       Bruce Bowen     4  SF        76.0          4.174750
11106   Dikembe Mutombo    -1   C         0.0          3.964356

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2005
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 451.46023172329353
R-squared (XGBoost): -0.08300866658883477

             Player_name  Rank Pos  Points_won  Predicted_points
10261  Metta World Peace    -1  SF         0.0        155.671570
10343      Kevin Garnett     9  PF        30.0         25.873329
10151      Manu Ginóbili   18T  SG         2.0         18.374460
10337      Allen Iverson    11  PG        10.0         18.044228
10592   Andrei Kirilenko    10  PF        25.0          9.503194
10355       LeBron James  -1.0  SF         0.0          6.866038
10380        Gary Payton    -1  PG         0.0          6.590764
10455        Ben Wallace     1   C       339.0          6.487709
10338       Shawn Marion     5  PF        57.0          5.390260
10352     Tyson Chandler   18T   C         2.0          4.963755

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2006
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 524.4536284134134
R-squared (XGBoost): 0.10226577687421656

             Player_name Rank Pos  Points_won  Predicted_points
9704        Marcus Camby    5   C        55.0         91.267075
9863        Shawn Marion    7  PF        33.0         57.478115
9730   Metta World Peace    4  SF        65.0         54.146175
9691    Andrei Kirilenko    3  SF       121.0         51.795570
9731   Metta World Peace    4  SF        65.0         46.669640
10009        Gary Payton   -1  PG         0.0         43.661327
10044         Tim Duncan    6  PF        42.0         32.649193
10028      Kevin Garnett  13T  PF         1.0         18.565117
10037     Gerald Wallace    9  SF        27.0         15.480175
10019      Shane Battier  10T  SF         3.0         13.509833

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2007
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 403.42045366581345
R-squared (XGBoost): 0.2727452986148615

            Player_name Rank Pos  Points_won  Predicted_points
9414        Ben Wallace    6   C        42.0        165.280457
9339        Bruce Bowen    2  SF       206.0        125.439240
9407       Marcus Camby    1   C       431.0         53.612000
9194         Josh Smith  21T  SF         3.0         51.971733
9356      Kevin Garnett  13T  PF         7.0         38.521442
9438         Tim Duncan    3   C       158.0         30.060469
9418       Shawn Marion    4  SF        93.0         27.913315
9577       Theo Ratliff   -1   C         0.0         16.963705
9559       Emeka Okafor  11T   C        10.0         15.020961
9566  Metta World Peace    8  SF        20.0          5.857099

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2008
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 326.50355395847805
R-squared (XGBoost): 0.4523089992274656

            Player_name Rank Pos  Points_won  Predicted_points
8731      Kevin Garnett    1  PF       493.0        135.018112
8891    Tayshaun Prince   10  SF        13.0         45.550930
8762       Marcus Camby    2   C       178.0         45.111317
8722      Shane Battier    3  SF       175.0         41.281048
8630         Josh Smith    6  PF        34.0         38.746620
8573         Tim Duncan    9   C        22.0         21.612803
8659  Metta World Peace  16T  SF         1.0         17.364534
9050      Dwight Howard   7T   C        24.0         10.440639
8633     Tyson Chandler   11   C        10.0          8.398619
8784        Bruce Bowen    4  SF        80.0          7.903960

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2009
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 246.19805386163688
R-squared (XGBoost): 0.6214769542672346

            Player_name  Rank Pos  Points_won  Predicted_points
8212      Dwight Howard     1   C       542.0        367.841736
8365      Kevin Garnett     8  PF        31.0        282.522522
8098        Bruce Bowen    -1  SF         0.0         34.638622
8274    Tayshaun Prince    -1  SF         0.0         28.285494
8426        Kobe Bryant     7  SG        43.0         27.401932
8556         Chris Paul     6  PG        49.0         24.242889
8484       LeBron James     2  SF       148.0         22.790110
8442  Metta World Peace     5  SF        54.0         20.112762
8430          Pau Gasol  -1.0   C         0.0          9.498925
8076        Mo Williams  -1.0  PG         0.0          8.545128

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2010
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 235.6475912846989
R-squared (XGBoost): 0.6741057069919737

            Player_name Rank Pos  Points_won  Predicted_points
8018      Dwight Howard    1   C       576.0        319.387268
7905          Raja Bell   -1  SG         0.0        112.215584
7911          Raja Bell   -1  SG         0.0        111.864273
8050  Metta World Peace    6  SF        29.0         42.501396
8041       LeBron James    4  SF        61.0         40.419888
7544        Dwyane Wade  10T  SG        13.0         27.618696
7564        Kobe Bryant   12  SG         9.0         21.686186
7553         Josh Smith    2  PF       136.0         19.284714
8016        Rajon Rondo    5  PG        55.0         16.120638
7939      Kevin Garnett   -1  PF         0.0         13.758352

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2011
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 246.5077729625782
R-squared (XGBoost): 0.6297512714747067

         Player_name  Rank Pos  Points_won  Predicted_points
7366   Dwight Howard     1   C       585.0        339.525604
7121   Kevin Garnett     2  PF        77.0        320.386566
7400       Luol Deng  10.0  SF        24.0         63.831295
7523    Andrew Bogut   6.0   C        32.0         54.303932
7288     Dwyane Wade    16  SG         8.0         45.216843
7231      Chris Paul   12T  PG        13.0         42.722527
7039     Kobe Bryant    11  SG        18.0         37.773075
7186    LeBron James     9  SF        25.0         26.334566
7321     Rajon Rondo     5  PG        45.0         21.583252
7490  Andre Iguodala     8  SF        29.0         19.186995

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2012
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 329.38456880356034
R-squared (XGBoost): 0.27215833885978036

         Player_name Rank Pos  Points_won  Predicted_points
6527     Serge Ibaka  2.0  PF       294.0        113.862579
6779     Dwyane Wade  18T  SG         1.0         24.834286
6747      Josh Smith   10  PF         9.0         23.898907
6620   Kenyon Martin   -1  PF         0.0         22.314243
6572    LeBron James    4  SF       112.0         20.404516
6484     Rajon Rondo   -1  PG         0.0         19.634174
6958      Tony Allen  6.0  SG        36.0         18.430988
6594  Gerald Wallace   -1  SF         0.0         17.117720
6595  Gerald Wallace   -1  SF         0.0         17.095436
6523  Andre Iguodala    7  SF        33.0         14.330049

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2013
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 178.17219570225325
R-squared (XGBoost): 0.2593945824076008

         Player_name Rank Pos  Points_won  Predicted_points
6355  Tyson Chandler   13   C        11.0        190.255264
6217      Marc Gasol    1   C       212.0        178.405823
6094     Mike Conley   21  PG         1.0        115.870110
6005     Serge Ibaka  3.0  PF       122.0        111.270088
6242     Paul George  8.0  SF        57.0         92.780556
5996   Dwight Howard   14   C         9.0         69.584763
6315      Josh Smith   -1  PF         0.0         67.712402
6419      Tim Duncan    6   C        94.0         51.545948
6245   Shane Battier   -1  SF         0.0         50.114910
6084    LeBron James    2  PF       149.0         49.209850

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2014
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 303.13198635923834
R-squared (XGBoost): 0.5383060067607444

         Player_name  Rank Pos  Points_won  Predicted_points
5847     Joakim Noah   1.0   C       555.0        192.072021
5804     Serge Ibaka   4.0  PF        79.0        106.559700
5805  Andre Iguodala     5  SF        47.0         78.343353
5952     Paul George   7.0  SF        30.0         46.538109
5641      Chris Paul   13T  PG         5.0         36.114712
5948     Roy Hibbert   2.0   C       166.0         33.472374
5514      Tim Duncan   13T   C         5.0         22.768452
5813    Andrew Bogut  10.0   C        11.0         20.858255
5895    Jimmy Butler    -1  SG         0.0         18.567411
5624   Anthony Davis    8T  PF        25.0         18.376650

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2015
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 219.5604661528759
R-squared (XGBoost): 0.5674341918652099

         Player_name  Rank Pos  Points_won  Predicted_points
5314   Kawhi Leonard     1  SF       333.0        207.868042
5393   Anthony Davis     4  PF       107.0         88.311310
5011  DeAndre Jordan   3.0   C       261.0         87.703110
5134     Rudy Gobert   5.0   C        33.0         43.057289
5107  Draymond Green     2  PF       317.0         41.377144
5227  Andre Iguodala    -1  SF         0.0         27.461128
5076    Nerlens Noel   15T   C         1.0         24.752136
5285    Andrew Bogut   6.0   C        31.0         23.990036
4860    Trevor Ariza   13T  SF         3.0         22.498552
5073   Stephen Curry  -1.0  PG         0.0         21.754051

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2016
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 257.2606747483661
R-squared (XGBoost): 0.7194188821647824

           Player_name  Rank Pos  Points_won  Predicted_points
4597    Draymond Green     2  PF       421.0        261.135315
4426     Kawhi Leonard     1  SF       547.0        260.402008
4570  Hassan Whiteside     3   C        83.0        207.270340
4474    DeAndre Jordan   4.0   C        50.0        106.903259
4820    Andre Drummond    10   C         3.0         57.264400
4782        Tim Duncan    -1   C         0.0         42.651108
4816     Stephen Curry  -1.0  PG         0.0         42.513062
4524      LeBron James   11T  SF         2.0         35.369167
4362        Chris Paul   13T  PG         1.0         16.796757
4580       Danny Green  -1.0  SG         0.0         14.563491

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2017
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 58.44990779772767
R-squared (XGBoost): 0.8916526430206972

                Player_name  Rank Pos  Points_won  Predicted_points
3989         Draymond Green     1  PF       434.0        366.832489
3977            Rudy Gobert   2.0   C       269.0        153.430573
4268          Kawhi Leonard     3  SF       182.0        150.103836
4212  Giannis Antetokounmpo  -1.0  SF         0.0         61.191025
3870       Hassan Whiteside    5T   C         3.0         59.666428
4129          Anthony Davis    -1   C         0.0         56.563732
4154         DeAndre Jordan  -1.0   C         0.0         31.081087
3988      Russell Westbrook    -1  PG         0.0         22.237335
4131            Edy Tavares  -1.0   C         0.0         16.114882
4051           Trevor Ariza    -1  SF         0.0         11.497125

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2018
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 245.75187967213597
R-squared (XGBoost): 0.43935266343809887

           Player_name  Rank Pos  Points_won  Predicted_points
3403       Rudy Gobert   1.0   C       466.0        131.790863
3177     Anthony Davis     3  PF       139.0         69.168724
3270    Draymond Green     6  PF        20.0         56.219467
3469     Kawhi Leonard    -1  SF         0.0         24.522312
3324    Andre Drummond   15T   C         1.0         23.661837
3598    Victor Oladipo   15T  SG         1.0         22.393887
3304      James Harden  -1.0  SG         0.0         16.994736
3312     Dwight Howard    -1   C         0.0         15.063429
3692    DeAndre Jordan  -1.0   C         0.0         14.594252
3655  Robert Covington   8.0  SF         8.0         14.253789

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2019
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 75.16976085291914
R-squared (XGBoost): 0.8265161412899823

                Player_name Rank Pos  Points_won  Predicted_points
2825            Rudy Gobert  1.0   C       411.0        404.462463
3114  Giannis Antetokounmpo  2.0  PF       280.0        142.915054
2980             Marc Gasol   -1   C         0.0         81.497894
2979             Marc Gasol   -1   C         0.0         74.766373
2932            Paul George  3.0  SF       150.0         68.024567
2876         Draymond Green   6T  PF         6.0         62.858253
2671          Anthony Davis   -1   C         0.0         44.131523
2562           Myles Turner  5.0   C        15.0         41.845055
3120       Hassan Whiteside   -1   C         0.0         31.109930
3148         Andre Drummond   -1   C         0.0         29.825584

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2020
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 136.97450114558845
R-squared (XGBoost): 0.6906916298884043

                Player_name  Rank Pos  Points_won  Predicted_points
2524            Rudy Gobert   3.0   C       187.0        271.099304
2127  Giannis Antetokounmpo   1.0  PF       432.0        212.999664
2270          Anthony Davis     2  PF       200.0        133.209961
2017       Hassan Whiteside    11   C         3.0        115.210625
2094            Brook Lopez  10.0   C         4.0         52.516685
2466         Jonathan Isaac  -1.0  PF         0.0         48.883099
2198          Kawhi Leonard    8T  SF         5.0         43.823685
2173           Clint Capela  -1.0   C         0.0         14.373383
2037              Kris Dunn  -1.0  PG         0.0         13.075952
2326           Myles Turner  -1.0   C         0.0         11.948667

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2021
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 292.9087164439288
R-squared (XGBoost): 0.3957501877639079

                Player_name  Rank Pos  Points_won  Predicted_points
1379            Rudy Gobert   1.0   C       464.0        198.608261
1719           Myles Turner   9.0   C         3.0        129.807953
1895  Giannis Antetokounmpo   5.0  PF        12.0        103.616447
1716           Clint Capela   6.0   C        10.0         79.427063
1845          Julius Randle  -1.0  PF         0.0         28.728823
1422         Draymond Green     3  PF        76.0         19.957186
1402             Marc Gasol    -1   C         0.0         18.767504
1604           Jimmy Butler    10  SF         2.0          9.756192
1554            Mike Conley    -1  PG         0.0          8.582668
1610      Spencer Dinwiddie  -1.0  SG         0.0          8.361738

---------------------------------------------------------------------
Selected Features Top  30  Test year :  2022
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 205.57683642299946
R-squared (XGBoost): 0.04478641578152742

                Player_name  Rank Pos  Points_won  Predicted_points
1022            Rudy Gobert   3.0   C       136.0        295.374847
992             Paul George  -1.0  PF         0.0         44.627857
1083      Russell Westbrook    -1  PG         0.0         44.615543
1111  Giannis Antetokounmpo   6.0  PF        58.0         39.678936
933              Al Horford     9   C         3.0         38.469410
713            Marcus Smart     1  PG       257.0         34.159737
758      Wendell Carter Jr.  -1.0  PF         0.0         33.957657
963           Jarrett Allen    -1   C         0.0         33.688778
627            Clint Capela  -1.0   C         0.0         26.563971
1007            Joel Embiid    -1   C         0.0         23.877789

---------------------------------------------------------------------

,Rank_1994,Rank_1995,Rank_1996,Rank_1997,Rank_1998,Rank_1999,Rank_2000,Rank_2001,Rank_2002,Rank_2003,...,Rank_2013,Rank_2014,Rank_2015,Rank_2016,Rank_2017,Rank_2018,Rank_2019,Rank_2020,Rank_2021,Rank_2022
0,1,1,3,2,1,4,5T,-1,1,1,...,13,1.0,1,2,1,1.0,1.0,3.0,1.0,3.0
1,2,4,6,-1,2,1,1,-1,3T,-1,...,1,4.0,4,1,2.0,3,2.0,1.0,9.0,-1.0
2,7T,2,4,1,3,5T,3T,1,-1,4,...,21,5,3.0,3,3,6,-1,2,5.0,-1
3,4,3,2,5,4,-1,2,1,2,13T,...,3.0,7.0,5.0,4.0,-1.0,-1,-1,11,6.0,6.0
4,3,6T,-1.0,3,5T,7T,-1,5T,-1,-1.0,...,8.0,13T,2,10,5T,15T,3.0,10.0,-1.0,9
5,10,6T,1,6T,11T,7T,7,3,-1,3,...,14,2.0,-1,-1,-1,15T,6T,-1.0,3,1
6,-1,5,5,4,9T,7T,3T,11T,3T,8,...,-1,13T,15T,-1.0,-1.0,-1.0,-1,8T,-1,-1.0
7,9,-1,7,-1.0,5T,3,-1,8T,-1,2,...,6,10.0,6.0,11T,-1,-1,5.0,-1.0,10,-1
8,-1,-1,8T,-1,11T,-1,8T,2,-1,5.0,...,-1,-1,13T,13T,-1.0,-1.0,-1,-1.0,-1,-1.0
9,5,-1,-1,-1,5T,-1,8T,11T,-1.0,6,...,2,8T,-1.0,-1.0,-1,8.0,-1,-1.0,-1.0,-1

In [17]:
top = top_40

rank_data_40 = pd.DataFrame()

for year in range(1994,2024):
    print("Selected Features Top ",40," Test year : ", year)
    Test_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] == year]
    Train_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] < year]
    
    X_train, y_train = Data_Organizer(Train_Data,top)
    X_test , y_test = Data_Organizer(Test_Data,top)
    
    # Initialize and train a XGBoost Regressor model
    xgb_model = XGBRegressor(n_estimators=200,max_depth = 5, random_state=42, n_jobs=-1)
    xgb_model.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred_xgb = xgb_model.predict(X_test)
    
    # Evaluate the model
    mse_xgb = mean_squared_error(y_test, y_pred_xgb)
    r2_xgb = r2_score(y_test, y_pred_xgb)
    
    # Mean Squared Error (MAE)
    print(f'Mean Squared Error (XGBoost): {mse_xgb}')
    print(f'R-squared (XGBoost): {r2_xgb}')
    
    Test_Data_copy = Test_Data.copy()
    Test_Data_copy.loc[:, 'Predicted_points'] = y_pred_xgb
    
    # Select only the desired columns
    Test_Data_concatenated = Test_Data_copy[['Player_name','Rank','Pos','Points_won', 'Predicted_points']]
    
    # Display the concatenated DataFrame sorted by 'Points_won'
    display(Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10))

    Test_Data_concatenated = Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10)

    if rank_data_40.empty:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_40 = pd.DataFrame(new_rank_column)
    else:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_40 = pd.concat([rank_data_40.reset_index(drop=True), new_rank_column.reset_index(drop=True)], axis=1)

    print("---------------------------------------------------------------------")

display(rank_data_40)

Selected Features Top  40  Test year :  1994
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.086059603054944
R-squared (XGBoost): -0.9183920341620857

           Player_name Rank Pos  Points_won  Predicted_points
15651  Hakeem Olajuwon    1   C        23.0         72.997879
15539   David Robinson    2   C        22.0          9.000184
15583  Mookie Blaylock   7T  PG         3.0          8.998990
15477   Scottie Pippen    4  SF        11.0          8.998990
15743  Dikembe Mutombo    3   C        19.0          1.226939
15540     Horace Grant   10  PF         1.0          1.226770
15796      Dan Majerle   -1  SG         0.0          1.226770
15649   Charles Oakley    9  PF         2.0          1.000250
15739    Patrick Ewing   -1   C         0.0          1.000208
15784      Gary Payton    5  PG         9.0          1.000081

---------------------------------------------------------------------
Selected Features Top  40  Test year :  1995
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 2.2209398651165593
R-squared (XGBoost): 0.646995602133532

           Player_name Rank Pos  Points_won  Predicted_points
15026  Dikembe Mutombo    1   C        45.0         16.906527
15199   Scottie Pippen    2  SF        16.0         15.170434
14994  Hakeem Olajuwon    3   C        13.0         14.279154
15113   David Robinson    4   C        12.0         13.737587
15151      Gary Payton   6T  PG         2.0         11.123900
15121    Dennis Rodman    5  PF        11.0          5.260120
15249    Nate McMillan   6T  PG         2.0          4.752166
15077  Mookie Blaylock   -1  PG         0.0          3.608401
15051    Patrick Ewing   -1   C         0.0          2.893458
15112     Horace Grant   -1  PF         0.0          2.300049

---------------------------------------------------------------------
Selected Features Top  40  Test year :  1996
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 6.9799201477373405
R-squared (XGBoost): 0.06969594230872933

           Player_name  Rank Pos  Points_won  Predicted_points
14887  Dikembe Mutombo     3   C        11.0         46.932522
14619   Michael Jordan     6  SG         7.0         15.510154
14839    Shawn Bradley  -1.0   C         0.0         15.439533
14844      Gary Payton     1  PG        56.0         14.683128
14897   David Robinson     4   C         9.0         13.309468
14797  Hakeem Olajuwon     5   C         8.0         12.511736
14749   Scottie Pippen     2  SF        15.0         11.672068
14909    Dennis Rodman     7  PF         4.0          8.580564
14555     Horace Grant    8T  PF         1.0          4.812449
14838   Charles Oakley    -1  PF         0.0          3.143180

---------------------------------------------------------------------
Selected Features Top  40  Test year :  1997
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 6.692723496731995
R-squared (XGBoost): 0.24887062559198747

           Player_name  Rank Pos  Points_won  Predicted_points
14149      Gary Payton     2  PG        25.0         54.985748
14210  Hakeem Olajuwon    -1   C         0.0         17.574280
14489  Dikembe Mutombo     1   C        60.0         17.538734
14081   Michael Jordan     5  SG         3.0         13.389184
14279     Horace Grant    6T  PF         1.0          9.792579
14164   Scottie Pippen     4  SF         4.0          9.305403
14333  Mookie Blaylock     3  PG        18.0          6.090715
14269    Dennis Rodman    -1  PF         0.0          4.077157
14277   David Robinson    -1   C         0.0          3.354080
14184       Grant Hill  -1.0  SF         0.0          2.458575

---------------------------------------------------------------------
Selected Features Top  40  Test year :  1998
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 0.6954488374734699
R-squared (XGBoost): 0.8882671821373994

           Player_name Rank Pos  Points_won  Predicted_points
13894  Dikembe Mutombo    1   C        39.0         51.678722
13764      Gary Payton    2  PG        37.0         25.013214
13605   David Robinson    3   C        10.0          9.405311
13836   Michael Jordan    4  SG         6.0          7.161119
13815  Mookie Blaylock   5T  PG         4.0          6.837985
13744        Bo Outlaw   5T  PF         4.0          3.422852
13842   Scottie Pippen   9T  SF         2.0          3.158046
13666    Brevin Knight  11T  PG         1.0          2.957662
13601    Kevin Garnett  11T  PF         1.0          1.216427
13889       Tim Duncan   5T  PF         4.0          1.119025

---------------------------------------------------------------------
Selected Features Top  40  Test year :  1999
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 15.83265167093995
R-squared (XGBoost): 0.06787220622532586

           Player_name Rank Pos  Points_won  Predicted_points
13269  Alonzo Mourning    1   C        89.0          3.186067
13434   David Robinson    4   C         3.0          3.105666
13406    Dennis Rodman   -1  PF         0.0          2.543316
13380  Mookie Blaylock   -1  PG         0.0          2.412133
13345     Kendall Gill   -1  SF         0.0          1.887930
13397   Scottie Pippen   7T  SF         1.0          1.820662
13424      Gary Payton    3  PG         6.0          1.781394
13237      Eddie Jones   7T  SF         1.0          1.544501
13445    Kevin Garnett   7T  PF         1.0          1.309650
13488       Tim Duncan   5T  PF         2.0          1.273236

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2000
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 1.300477522989746
R-squared (XGBoost): 0.8658744826737981

             Player_name Rank Pos  Points_won  Predicted_points
12956    Alonzo Mourning    1   C        62.0         56.991600
12708        Gary Payton   5T  PG         4.0         24.266018
12909    Dikembe Mutombo   3T   C        11.0         17.598251
12725   Shaquille O'Neal    2   C        21.0         14.778468
12841      Kevin Garnett    7  PF         2.0          5.806324
12741        Eddie Jones   3T  SG        11.0          4.335598
12827     Scottie Pippen   8T  SF         1.0          3.515474
12989  Clifford Robinson   8T  SF         1.0          2.944238
12733          Bo Outlaw   8T  PF         1.0          2.587922
12830         Tim Duncan   -1  PF         0.0          1.780708

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2001
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 9.593231181888711
R-squared (XGBoost): 0.16138962379738797

            Player_name Rank Pos  Points_won  Predicted_points
12427       Gary Payton   -1  PG         0.0         25.315866
12210   Alonzo Mourning   -1   C         0.0         10.282433
12510   Dikembe Mutombo    1   C        48.0          9.794748
12512   Dikembe Mutombo    1   C        48.0          5.860273
12514     Allen Iverson  11T  SG         1.0          4.422275
12403  Shaquille O'Neal   8T   C         2.0          4.340496
12460     Kevin Garnett    2  PF        26.0          4.092235
12113      Theo Ratliff    7   C         4.0          3.372296
12106    David Robinson   5T   C         6.0          3.366729
12285     Doug Christie  4.0  SG         9.0          3.234117

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2002
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 17.690788647075063
R-squared (XGBoost): 0.38095102726567454

            Player_name Rank Pos  Points_won  Predicted_points
11941       Ben Wallace    1   C       116.0         38.927410
12003   Dikembe Mutombo   3T   C         1.0         37.875984
12035   Alonzo Mourning   -1   C         0.0         20.909899
11936     Kevin Garnett    2  PF         2.0         15.984367
11852        Tim Duncan   -1  PF         0.0         15.633591
11927  Shaquille O'Neal   -1   C         0.0          6.303357
12005       Kobe Bryant   3T  SG         1.0          6.107523
12041       Eddie Jones   -1  SG         0.0          5.309746
11831     Anthony Mason   -1  PF         0.0          3.563856
11654     Allen Iverson   -1  SG         0.0          3.211250

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2003
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 667.8299908321459
R-squared (XGBoost): 0.0664509396252071

             Player_name  Rank Pos  Points_won  Predicted_points
11137        Ben Wallace     1   C       531.0         19.087309
11176        Gary Payton    11  PG         5.0         12.250806
11559         Jason Kidd    -1  PG         0.0         11.638952
11505      Dirk Nowitzki  -1.0  PF         0.0          9.430222
11412       Shawn Marion   13T  SF         3.0          9.046059
11405         Tim Duncan     4  PF        90.0          7.821511
11183      Kevin Garnett     3  PF       121.0          6.958404
11347      Doug Christie   5.0  SG        85.0          3.858119
11494   Shaquille O'Neal   13T   C         3.0          3.434531
11514  Metta World Peace     2  SF       122.0          2.866159

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2004
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 573.1930580088682
R-squared (XGBoost): 0.17077388948003203

             Player_name  Rank Pos  Points_won  Predicted_points
11127      Kevin Garnett     6  PF        36.0        121.487038
10663        Ben Wallace     2   C       325.0         61.637463
10722  Metta World Peace     1  SF       476.0         35.113377
10818         Tim Duncan     7  PF         8.0         31.741869
10721        Gary Payton    -1  PG         0.0         16.819683
11017    Rasheed Wallace  -1.0  PF         0.0         13.807368
10664       Theo Ratliff     3   C        90.0          6.505388
11051        Eddie Jones    -1  SG         0.0          4.620617
10871   Andrei Kirilenko     5  PF        67.0          4.133406
10650       Theo Ratliff     3   C        90.0          3.143094

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2005
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 450.5127632892256
R-squared (XGBoost): -0.08073578305821227

             Player_name Rank Pos  Points_won  Predicted_points
10261  Metta World Peace   -1  SF         0.0        157.711899
10592   Andrei Kirilenko   10  PF        25.0         24.374111
10343      Kevin Garnett    9  PF        30.0         19.436544
10337      Allen Iverson   11  PG        10.0         14.356086
10151      Manu Ginóbili  18T  SG         2.0          8.648034
10326         Tim Duncan    4  PF        81.0          6.962412
10455        Ben Wallace    1   C       339.0          5.357133
10338       Shawn Marion    5  PF        57.0          5.141182
10380        Gary Payton   -1  PG         0.0          4.780671
10225        Bruce Bowen    2  SF       247.0          4.628539

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2006
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 439.17485050163714
R-squared (XGBoost): 0.2482418428027685

             Player_name Rank Pos  Points_won  Predicted_points
9704        Marcus Camby    5   C        55.0        150.381531
9731   Metta World Peace    4  SF        65.0         84.141365
9691    Andrei Kirilenko    3  SF       121.0         78.116058
9610         Bruce Bowen    2  SF       308.0         66.207893
9730   Metta World Peace    4  SF        65.0         54.689728
10044         Tim Duncan    6  PF        42.0         34.657597
9863        Shawn Marion    7  PF        33.0         34.553249
9841         Ben Wallace    1   C       420.0         29.337820
9899       Dwight Howard   -1  PF         0.0         28.149479
10028      Kevin Garnett  13T  PF         1.0         19.574940

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2007
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 419.9254136460227
R-squared (XGBoost): 0.24299145338289896

            Player_name Rank Pos  Points_won  Predicted_points
9414        Ben Wallace    6   C        42.0        181.707703
9339        Bruce Bowen    2  SF       206.0        173.199844
9210        Eddie Jones   -1  SG         0.0        119.794502
9407       Marcus Camby    1   C       431.0         59.973434
9418       Shawn Marion    4  SF        93.0         39.424019
9356      Kevin Garnett  13T  PF         7.0         35.562428
9438         Tim Duncan    3   C       158.0         15.536194
9559       Emeka Okafor  11T   C        10.0         14.351539
9313   Andrei Kirilenko  13T  SF         7.0          8.913738
9566  Metta World Peace    8  SF        20.0          7.210245

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2008
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 299.7803900301477
R-squared (XGBoost): 0.49713557528849384

            Player_name Rank Pos  Points_won  Predicted_points
8731      Kevin Garnett    1  PF       493.0        135.763519
8762       Marcus Camby    2   C       178.0         82.127258
8722      Shane Battier    3  SF       175.0         67.245583
8891    Tayshaun Prince   10  SF        13.0         37.359005
8659  Metta World Peace  16T  SF         1.0         35.435219
8573         Tim Duncan    9   C        22.0         20.930851
8568       Shawn Marion   -1  PF         0.0         19.465853
8588       Shawn Marion   -1  PF         0.0         19.343348
8571        Kobe Bryant    5  SG        40.0         16.449877
8678        Rajon Rondo  16T  PG         1.0         14.444821

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2009
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 242.9503651131505
R-squared (XGBoost): 0.6264701904743737

            Player_name Rank Pos  Points_won  Predicted_points
8212      Dwight Howard    1   C       542.0        350.437531
8365      Kevin Garnett    8  PF        31.0        277.507812
8442  Metta World Peace    5  SF        54.0         61.923870
8556         Chris Paul    6  PG        49.0         34.373390
8426        Kobe Bryant    7  SG        43.0         33.192238
8098        Bruce Bowen   -1  SF         0.0         26.074970
8484       LeBron James    2  SF       148.0         19.728889
8507        Dwyane Wade    3  SG        90.0         19.682135
8390        Elton Brand   -1  PF         0.0          9.088531
8093       Marcus Camby  16T   C         1.0          7.095505

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2010
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 247.26422555186107
R-squared (XGBoost): 0.6580402136381469

            Player_name Rank Pos  Points_won  Predicted_points
8018      Dwight Howard    1   C       576.0        292.244171
7911          Raja Bell   -1  SG         0.0         93.726280
7905          Raja Bell   -1  SG         0.0         92.627869
8041       LeBron James    4  SF        61.0         37.492516
7544        Dwyane Wade  10T  SG        13.0         26.126019
7553         Josh Smith    2  PF       136.0         20.803579
8016        Rajon Rondo    5  PG        55.0         18.428190
8050  Metta World Peace    6  SF        29.0         18.375475
7797       Marcus Camby  10T  PF        13.0         13.475636
7564        Kobe Bryant   12  SG         9.0         13.240737

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2011
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 282.87720300462104
R-squared (XGBoost): 0.5751252648850476

          Player_name  Rank Pos  Points_won  Predicted_points
7121    Kevin Garnett     2  PF        77.0        345.747803
7366    Dwight Howard     1   C       585.0        329.456238
7400        Luol Deng  10.0  SF        24.0         68.073074
7231       Chris Paul   12T  PG        13.0         59.979088
7523     Andrew Bogut   6.0   C        32.0         51.771912
7508       Josh Smith    25  PF         1.0         44.112331
7321      Rajon Rondo     5  PG        45.0         31.688980
7288      Dwyane Wade    16  SG         8.0         24.339634
7039      Kobe Bryant    11  SG        18.0         23.199663
7515  Tayshaun Prince    -1  SF         0.0         15.750889

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2012
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 300.6102396256535
R-squared (XGBoost): 0.3357410246641459

         Player_name  Rank Pos  Points_won  Predicted_points
6510   Dwight Howard     3   C       186.0        104.470131
6527     Serge Ibaka   2.0  PF       294.0         91.399437
6523  Andre Iguodala     7  SF        33.0         55.510666
6987   Kevin Garnett     5   C        44.0         40.865318
6779     Dwyane Wade   18T  SG         1.0         39.285164
6958      Tony Allen   6.0  SG        36.0         32.192425
6572    LeBron James     4  SF       112.0         31.894941
6874     Paul George  -1.0  SG         0.0         28.043158
6747      Josh Smith    10  PF         9.0         27.229685
6938      Marc Gasol   12T   C         5.0         17.488146

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2013
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 119.91614073222672
R-squared (XGBoost): 0.501546562116389

         Player_name Rank Pos  Points_won  Predicted_points
6217      Marc Gasol    1   C       212.0        247.812988
6005     Serge Ibaka  3.0  PF       122.0        159.541489
6355  Tyson Chandler   13   C        11.0        126.976585
6094     Mike Conley   21  PG         1.0        100.178078
6084    LeBron James    2  PF       149.0         88.440002
6242     Paul George  8.0  SF        57.0         88.270317
6315      Josh Smith   -1  PF         0.0         55.206444
6245   Shane Battier   -1  SF         0.0         47.221298
5996   Dwight Howard   14   C         9.0         46.848316
6419      Tim Duncan    6   C        94.0         32.912788

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2014
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 109.34996135878494
R-squared (XGBoost): 0.8334513591697807

         Player_name Rank Pos  Points_won  Predicted_points
5847     Joakim Noah  1.0   C       555.0        383.164337
5804     Serge Ibaka  4.0  PF        79.0         91.726921
5716      Marc Gasol  15T   C         4.0         82.756271
5898  DeAndre Jordan  3.0   C       121.0         80.667953
5952     Paul George  7.0  SF        30.0         61.829834
5624   Anthony Davis   8T  PF        25.0         54.065331
5805  Andre Iguodala    5  SF        47.0         44.935390
5514      Tim Duncan  13T   C         5.0         39.689560
5948     Roy Hibbert  2.0   C       166.0         37.100086
5895    Jimmy Butler   -1  SG         0.0         33.933666

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2015
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 234.27406962406332
R-squared (XGBoost): 0.5384462693689192

         Player_name  Rank Pos  Points_won  Predicted_points
5314   Kawhi Leonard     1  SF       333.0        181.705856
5011  DeAndre Jordan   3.0   C       261.0         99.959633
4908   Kevin Garnett    -1  PF         0.0         75.476242
5393   Anthony Davis     4  PF       107.0         60.628796
5107  Draymond Green     2  PF       317.0         59.924526
5349      Chris Paul   15T  PG         1.0         53.007618
4915      Tim Duncan     8   C        12.0         46.028580
5134     Rudy Gobert   5.0   C        33.0         36.717705
5017    Paul Millsap  -1.0  PF         0.0         35.802700
4860    Trevor Ariza   13T  SF         3.0         34.260387

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2016
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 272.89522673433015
R-squared (XGBoost): 0.7023670724493433

           Player_name  Rank Pos  Points_won  Predicted_points
4426     Kawhi Leonard     1  SF       547.0        332.490875
4597    Draymond Green     2  PF       421.0        190.338684
4474    DeAndre Jordan   4.0   C        50.0        180.249771
4570  Hassan Whiteside     3   C        83.0        161.307236
4820    Andre Drummond    10   C         3.0         95.005371
4464    Andre Iguodala    -1  SF         0.0         89.785240
4580       Danny Green  -1.0  SG         0.0         32.431736
4773      Andrew Bogut  -1.0   C         0.0         29.744944
4524      LeBron James   11T  SF         2.0         28.842279
4816     Stephen Curry  -1.0  PG         0.0         22.057459

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2017
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 219.10287707082477
R-squared (XGBoost): 0.5938536341351106

                Player_name  Rank Pos  Points_won  Predicted_points
3989         Draymond Green     1  PF       434.0        217.401001
4129          Anthony Davis    -1   C         0.0        127.048447
3977            Rudy Gobert   2.0   C       269.0        118.011162
3870       Hassan Whiteside    5T   C         3.0         62.357647
4131            Edy Tavares  -1.0   C         0.0         46.159996
4154         DeAndre Jordan  -1.0   C         0.0         25.181801
4268          Kawhi Leonard     3  SF       182.0         23.145638
4212  Giannis Antetokounmpo  -1.0  SF         0.0         20.037060
4143       Robert Covington   4.0  SF         4.0         14.454164
3988      Russell Westbrook    -1  PG         0.0         14.010193

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2018
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 343.42829350564904
R-squared (XGBoost): 0.21651806565705

           Player_name  Rank Pos  Points_won  Predicted_points
3177     Anthony Davis     3  PF       139.0         61.316334
3403       Rudy Gobert   1.0   C       466.0         56.800556
3270    Draymond Green     6  PF        20.0         54.302895
3324    Andre Drummond   15T   C         1.0         50.475067
3598    Victor Oladipo   15T  SG         1.0         38.955978
3469     Kawhi Leonard    -1  SF         0.0         33.308983
3312     Dwight Howard    -1   C         0.0         21.926441
3304      James Harden  -1.0  SG         0.0         19.694042
3655  Robert Covington   8.0  SF         8.0         18.752668
3583      Clint Capela  14.0   C         2.0         10.317719

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2019
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 66.04924507433952
R-squared (XGBoost): 0.8475653271958618

                Player_name  Rank Pos  Points_won  Predicted_points
2825            Rudy Gobert   1.0   C       411.0        487.024963
3114  Giannis Antetokounmpo   2.0  PF       280.0        231.678787
2671          Anthony Davis    -1   C         0.0         76.369919
2876         Draymond Green    6T  PF         6.0         67.871506
2980             Marc Gasol    -1   C         0.0         62.640335
2562           Myles Turner   5.0   C        15.0         59.752239
2979             Marc Gasol    -1   C         0.0         57.318962
2932            Paul George   3.0  SF       150.0         42.778839
3120       Hassan Whiteside    -1   C         0.0         27.969286
2738            Brook Lopez  -1.0   C         0.0         26.164276

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2020
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 119.6635251033075
R-squared (XGBoost): 0.7297823346538675

                Player_name  Rank Pos  Points_won  Predicted_points
2524            Rudy Gobert   3.0   C       187.0        255.006348
2127  Giannis Antetokounmpo   1.0  PF       432.0        242.445068
2198          Kawhi Leonard    8T  SF         5.0        106.628052
2270          Anthony Davis     2  PF       200.0        101.963654
2017       Hassan Whiteside    11   C         3.0         88.679596
2094            Brook Lopez  10.0   C         4.0         24.530718
2187         Andre Drummond    8T   C         5.0         19.212999
2259           LeBron James    -1  PG         0.0         15.438788
2340            Joel Embiid    -1   C         0.0         14.841841
2132             Kyle Lowry    -1  PG         0.0         12.972928

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2021
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 259.8327997425359
R-squared (XGBoost): 0.4639834472551092

                Player_name Rank Pos  Points_won  Predicted_points
1379            Rudy Gobert  1.0   C       464.0        198.848877
1719           Myles Turner  9.0   C         3.0         89.534073
1716           Clint Capela  6.0   C        10.0         69.512070
1422         Draymond Green    3  PF        76.0         64.013496
1741       Matisse Thybulle  11T  SG         1.0         26.440184
1554            Mike Conley   -1  PG         0.0         17.928875
1628         Andre Drummond   -1   C         0.0         16.867672
1629         Andre Drummond   -1   C         0.0         12.573088
1586          Kawhi Leonard   -1  SF         0.0         10.695050
1895  Giannis Antetokounmpo  5.0  PF        12.0          8.895785

---------------------------------------------------------------------
Selected Features Top  40  Test year :  2022
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 172.92810684085617
R-squared (XGBoost): 0.19648886702544432

                Player_name  Rank Pos  Points_won  Predicted_points
1022            Rudy Gobert   3.0   C       136.0        197.809143
1111  Giannis Antetokounmpo   6.0  PF        58.0         66.211876
933              Al Horford     9   C         3.0         54.628956
1306            Bam Adebayo   4.0   C       128.0         51.116600
997       Jaren Jackson Jr.   5.0  PF        99.0         46.641598
1046        Sekou Doumbouya  -1.0  PF         0.0         41.604797
1176            Jae Crowder    -1  PF         0.0         41.477203
1123         Draymond Green    10  PF         2.0         37.103241
1009          Anthony Davis    -1   C         0.0         24.488304
1178       Matisse Thybulle    11  SG         1.0         23.583099

---------------------------------------------------------------------

,Rank_1994,Rank_1995,Rank_1996,Rank_1997,Rank_1998,Rank_1999,Rank_2000,Rank_2001,Rank_2002,Rank_2003,...,Rank_2013,Rank_2014,Rank_2015,Rank_2016,Rank_2017,Rank_2018,Rank_2019,Rank_2020,Rank_2021,Rank_2022
0,1,1,3,2,1,1,1,-1,1,1,...,1,1.0,1,1,1,3,1.0,3.0,1.0,3.0
1,2,2,6,-1,2,4,5T,-1,3T,11,...,3.0,4.0,3.0,2,-1,1.0,2.0,1.0,9.0,6.0
2,7T,3,-1.0,1,3,-1,3T,1,-1,-1,...,13,15T,-1,4.0,2.0,6,-1,8T,6.0,9
3,4,4,1,5,4,-1,2,1,2,-1.0,...,21,3.0,4,3,5T,15T,6T,2,3,4.0
4,3,6T,4,6T,5T,-1,7,11T,-1,13T,...,2,7.0,2,10,-1.0,15T,-1,11,11T,5.0
5,10,5,5,4,5T,7T,3T,8T,-1,4,...,8.0,8T,15T,-1,-1.0,-1,5.0,10.0,-1,-1.0
6,-1,6T,2,3,9T,3,8T,2,3T,3,...,-1,5,8,-1.0,3,-1,-1,8T,-1,-1
7,9,-1,7,-1,11T,7T,8T,7,-1,5.0,...,-1,13T,5.0,-1.0,-1.0,-1.0,3.0,-1,-1,10
8,-1,-1,8T,-1,11T,7T,8T,5T,-1,13T,...,14,2.0,-1.0,11T,4.0,8.0,-1,-1,-1,-1
9,5,-1,-1,-1.0,5T,5T,-1,4.0,-1,2,...,6,-1,13T,-1.0,-1,14.0,-1.0,-1,5.0,11

In [18]:
top = top_50

rank_data_50 = pd.DataFrame()

for year in range(1994,2024):
    print("Selected Features Top ",50," Test year : ", year)
    Test_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] == year]
    Train_Data = all_players_w_add_sorted[all_players_w_add_sorted['Year'] < year]
    
    X_train, y_train = Data_Organizer(Train_Data,top)
    X_test , y_test = Data_Organizer(Test_Data,top)
    
    # Initialize and train a XGBoost Regressor model
    xgb_model = XGBRegressor(n_estimators=200,max_depth = 5, random_state=42, n_jobs=-1)
    xgb_model.fit(X_train, y_train)
    
    # Make predictions on the test set
    y_pred_xgb = xgb_model.predict(X_test)
    
    # Evaluate the model
    mse_xgb = mean_squared_error(y_test, y_pred_xgb)
    r2_xgb = r2_score(y_test, y_pred_xgb)
    
    # Mean Squared Error (MAE)
    print(f'Mean Squared Error (XGBoost): {mse_xgb}')
    print(f'R-squared (XGBoost): {r2_xgb}')
    
    Test_Data_copy = Test_Data.copy()
    Test_Data_copy.loc[:, 'Predicted_points'] = y_pred_xgb
    
    # Select only the desired columns
    Test_Data_concatenated = Test_Data_copy[['Player_name','Rank','Pos','Points_won', 'Predicted_points']]
    
    # Display the concatenated DataFrame sorted by 'Points_won'
    display(Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10))

    Test_Data_concatenated = Test_Data_concatenated.sort_values(by='Predicted_points', ascending=False).head(10)

    if rank_data_50.empty:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_50 = pd.DataFrame(new_rank_column)
    else:
        new_rank_column = Test_Data_concatenated['Rank'].head(10).rename(f'Rank_{year}')
        rank_data_50 = pd.concat([rank_data_50.reset_index(drop=True), new_rank_column.reset_index(drop=True)], axis=1)

    print("---------------------------------------------------------------------")

display(rank_data_50)

Selected Features Top  50  Test year :  1994
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 6.987566875358309
R-squared (XGBoost): -0.8917273326466395

           Player_name Rank Pos  Points_won  Predicted_points
15651  Hakeem Olajuwon    1   C        23.0         72.997887
15539   David Robinson    2   C        22.0          9.000278
15477   Scottie Pippen    4  SF        11.0          8.998887
15583  Mookie Blaylock   7T  PG         3.0          8.408022
15739    Patrick Ewing   -1   C         0.0          2.131721
15649   Charles Oakley    9  PF         2.0          2.131721
15743  Dikembe Mutombo    3   C        19.0          2.131721
15540     Horace Grant   10  PF         1.0          2.131156
15525    Dennis Rodman    6  PF         8.0          2.131156
15796      Dan Majerle   -1  SG         0.0          1.952294

---------------------------------------------------------------------
Selected Features Top  50  Test year :  1995
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 2.2099422022585866
R-squared (XGBoost): 0.6487436113507529

           Player_name Rank Pos  Points_won  Predicted_points
15026  Dikembe Mutombo    1   C        45.0         16.944262
15199   Scottie Pippen    2  SF        16.0         15.477461
14994  Hakeem Olajuwon    3   C        13.0         14.101201
15113   David Robinson    4   C        12.0         13.980199
15151      Gary Payton   6T  PG         2.0         11.054773
15121    Dennis Rodman    5  PF        11.0          5.250000
15249    Nate McMillan   6T  PG         2.0          4.728012
15077  Mookie Blaylock   -1  PG         0.0          3.531059
15051    Patrick Ewing   -1   C         0.0          2.770128
15112     Horace Grant   -1  PF         0.0          2.325254

---------------------------------------------------------------------
Selected Features Top  50  Test year :  1996
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.041282888786829
R-squared (XGBoost): 0.061517337714248055

           Player_name  Rank Pos  Points_won  Predicted_points
14887  Dikembe Mutombo     3   C        11.0         47.005959
14619   Michael Jordan     6  SG         7.0         17.111574
14839    Shawn Bradley  -1.0   C         0.0         15.046276
14844      Gary Payton     1  PG        56.0         14.422301
14897   David Robinson     4   C         9.0         12.641591
14797  Hakeem Olajuwon     5   C         8.0         11.455115
14749   Scottie Pippen     2  SF        15.0         10.424467
14909    Dennis Rodman     7  PF         4.0          6.866065
14555     Horace Grant    8T  PF         1.0          5.471053
14838   Charles Oakley    -1  PF         0.0          3.041690

---------------------------------------------------------------------
Selected Features Top  50  Test year :  1997
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 6.797129820781214
R-squared (XGBoost): 0.2371530255886969

           Player_name  Rank Pos  Points_won  Predicted_points
14149      Gary Payton     2  PG        25.0         55.433521
14210  Hakeem Olajuwon    -1   C         0.0         18.054770
14489  Dikembe Mutombo     1   C        60.0         17.651308
14081   Michael Jordan     5  SG         3.0         13.304023
14164   Scottie Pippen     4  SF         4.0         11.242983
14279     Horace Grant    6T  PF         1.0          8.251586
14269    Dennis Rodman    -1  PF         0.0          5.486901
14333  Mookie Blaylock     3  PG        18.0          5.463984
14141    Shawn Bradley  -1.0   C         0.0          2.985976
14277   David Robinson    -1   C         0.0          2.819673

---------------------------------------------------------------------
Selected Features Top  50  Test year :  1998
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 0.6359617707886422
R-squared (XGBoost): 0.8978245459993093

           Player_name Rank Pos  Points_won  Predicted_points
13894  Dikembe Mutombo    1   C        39.0         49.892570
13764      Gary Payton    2  PG        37.0         24.965147
13815  Mookie Blaylock   5T  PG         4.0          8.238291
13605   David Robinson    3   C        10.0          7.597189
13836   Michael Jordan    4  SG         6.0          7.489866
13842   Scottie Pippen   9T  SF         2.0          4.334728
13744        Bo Outlaw   5T  PF         4.0          3.251602
13889       Tim Duncan   5T  PF         4.0          2.216381
13666    Brevin Knight  11T  PG         1.0          1.591397
13740  Hakeem Olajuwon   -1   C         0.0          1.296674

---------------------------------------------------------------------
Selected Features Top  50  Test year :  1999
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 16.073233150700254
R-squared (XGBoost): 0.05370826902688264

           Player_name  Rank Pos  Points_won  Predicted_points
13380  Mookie Blaylock    -1  PG         0.0          2.680011
13269  Alonzo Mourning     1   C        89.0          2.551879
13434   David Robinson     4   C         3.0          2.172885
13488       Tim Duncan    5T  PF         2.0          2.083747
13345     Kendall Gill    -1  SF         0.0          1.923461
13406    Dennis Rodman    -1  PF         0.0          1.596956
13237      Eddie Jones    7T  SF         1.0          1.285906
13182  Dikembe Mutombo     2   C        10.0          0.891151
13397   Scottie Pippen    7T  SF         1.0          0.836663
13295  Antonio McDyess  -1.0   C         0.0          0.753981

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2000
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 2.3394421578806557
R-squared (XGBoost): 0.7587202514972315

             Player_name Rank Pos  Points_won  Predicted_points
12956    Alonzo Mourning    1   C        62.0         38.407555
12708        Gary Payton   5T  PG         4.0         24.176577
12725   Shaquille O'Neal    2   C        21.0         15.747038
12909    Dikembe Mutombo   3T   C        11.0         13.612671
12841      Kevin Garnett    7  PF         2.0          5.299309
12741        Eddie Jones   3T  SG        11.0          3.783254
12989  Clifford Robinson   8T  SF         1.0          3.502565
12750    Hakeem Olajuwon   -1   C         0.0          2.917383
12733          Bo Outlaw   8T  PF         1.0          2.769389
12827     Scottie Pippen   8T  SF         1.0          2.638937

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2001
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 7.18227112567753
R-squared (XGBoost): 0.37214823905580463

            Player_name Rank Pos  Points_won  Predicted_points
12210   Alonzo Mourning   -1   C         0.0         17.927015
12512   Dikembe Mutombo    1   C        48.0         17.500755
12510   Dikembe Mutombo    1   C        48.0          9.147988
12403  Shaquille O'Neal   8T   C         2.0          5.630069
12113      Theo Ratliff    7   C         4.0          4.046399
12460     Kevin Garnett    2  PF        26.0          3.501375
12492       Kobe Bryant  11T  SG         1.0          3.461818
12514     Allen Iverson  11T  SG         1.0          3.230341
12271        Tim Duncan    3  PF        14.0          3.119702
12106    David Robinson   5T   C         6.0          2.261501

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2002
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 19.301943768912622
R-squared (XGBoost): 0.3245723127274682

            Player_name Rank Pos  Points_won  Predicted_points
11950       Gary Payton   -1  PG         0.0         28.534903
11941       Ben Wallace    1   C       116.0         28.525963
11852        Tim Duncan   -1  PF         0.0         16.721775
11936     Kevin Garnett    2  PF         2.0         12.906384
12003   Dikembe Mutombo   3T   C         1.0          7.877732
12035   Alonzo Mourning   -1   C         0.0          6.438097
12005       Kobe Bryant   3T  SG         1.0          5.905837
11927  Shaquille O'Neal   -1   C         0.0          5.373309
12041       Eddie Jones   -1  SG         0.0          4.962766
11831     Anthony Mason   -1  PF         0.0          3.591235

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2003
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 656.003582403017
R-squared (XGBoost): 0.08298289031353245

           Player_name  Rank Pos  Points_won  Predicted_points
11137      Ben Wallace     1   C       531.0         24.436874
11461  Dikembe Mutombo    -1   C         0.0         18.636679
11412     Shawn Marion   13T  SF         3.0         13.344882
11405       Tim Duncan     4  PF        90.0          9.128772
11559       Jason Kidd    -1  PG         0.0          8.071518
11347    Doug Christie   5.0  SG        85.0          5.113246
11183    Kevin Garnett     3  PF       121.0          4.998171
11505    Dirk Nowitzki  -1.0  PF         0.0          4.803512
11176      Gary Payton    11  PG         5.0          4.613437
11411    Allen Iverson     6  SG        29.0          4.351151

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2004
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 576.7734347293159
R-squared (XGBoost): 0.16559423522461159

             Player_name  Rank Pos  Points_won  Predicted_points
11127      Kevin Garnett     6  PF        36.0        121.643456
10663        Ben Wallace     2   C       325.0         49.901436
10722  Metta World Peace     1  SF       476.0         38.745922
10721        Gary Payton    -1  PG         0.0         29.252621
10818         Tim Duncan     7  PF         8.0         13.810133
10650       Theo Ratliff     3   C        90.0          7.481415
10664       Theo Ratliff     3   C        90.0          7.037235
10871   Andrei Kirilenko     5  PF        67.0          5.916423
11017    Rasheed Wallace  -1.0  PF         0.0          5.058320
11051        Eddie Jones    -1  SG         0.0          4.806168

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2005
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 431.46005528450434
R-squared (XGBoost): -0.035030211578891635

             Player_name Rank Pos  Points_won  Predicted_points
10261  Metta World Peace   -1  SF         0.0        134.936829
10326         Tim Duncan    4  PF        81.0         58.245754
10343      Kevin Garnett    9  PF        30.0         21.662609
10352     Tyson Chandler  18T   C         2.0         14.346791
10240    Alonzo Mourning   -1   C         0.0         13.862353
10592   Andrei Kirilenko   10  PF        25.0         13.391934
10276    Dikembe Mutombo   -1   C         0.0          9.864595
10151      Manu Ginóbili  18T  SG         2.0          5.850812
10225        Bruce Bowen    2  SF       247.0          5.209957
10337      Allen Iverson   11  PG        10.0          5.179377

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2006
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 468.98394487299095
R-squared (XGBoost): 0.1972160843224482

            Player_name Rank Pos  Points_won  Predicted_points
9704       Marcus Camby    5   C        55.0        136.981079
9691   Andrei Kirilenko    3  SF       121.0         71.683487
9863       Shawn Marion    7  PF        33.0         47.106476
10044        Tim Duncan    6  PF        42.0         39.766624
9841        Ben Wallace    1   C       420.0         37.889168
9610        Bruce Bowen    2  SF       308.0         35.445820
9899      Dwight Howard   -1  PF         0.0         24.164574
10028     Kevin Garnett  13T  PF         1.0         22.786079
10019     Shane Battier  10T  SF         3.0          9.544336
10037    Gerald Wallace    9  SF        27.0          9.483803

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2007
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 413.9612038397351
R-squared (XGBoost): 0.2537432622767115

          Player_name Rank Pos  Points_won  Predicted_points
9414      Ben Wallace    6   C        42.0        249.827972
9339      Bruce Bowen    2  SF       206.0        191.278519
9210      Eddie Jones   -1  SG         0.0         92.908150
9407     Marcus Camby    1   C       431.0         80.295898
9438       Tim Duncan    3   C       158.0         33.159199
9418     Shawn Marion    4  SF        93.0         31.345524
9356    Kevin Garnett  13T  PF         7.0         22.674370
9355    Shane Battier    5  SF        86.0         14.411188
9559     Emeka Okafor  11T   C        10.0         13.003575
9344  Dikembe Mutombo   -1   C         0.0         12.142738

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2008
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 363.18557914875214
R-squared (XGBoost): 0.39077700411362537

           Player_name Rank Pos  Points_won  Predicted_points
8722     Shane Battier    3  SF       175.0        156.492538
8784       Bruce Bowen    4  SF        80.0        139.500504
8762      Marcus Camby    2   C       178.0        109.894035
8931  Andrei Kirilenko  16T  SF         1.0        109.379692
8731     Kevin Garnett    1  PF       493.0         87.399895
8891   Tayshaun Prince   10  SF        13.0         60.625629
8738       James Posey   -1  PF         0.0         42.746967
8949   Rasheed Wallace   12   C         9.0         29.636402
8571       Kobe Bryant    5  SG        40.0         24.912466
9050     Dwight Howard   7T   C        24.0         23.386133

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2009
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 275.0679770999621
R-squared (XGBoost): 0.5770902050511604

            Player_name  Rank Pos  Points_won  Predicted_points
8212      Dwight Howard     1   C       542.0        371.740692
8365      Kevin Garnett     8  PF        31.0        313.333008
8098        Bruce Bowen    -1  SF         0.0         41.775791
8556         Chris Paul     6  PG        49.0         41.271339
8483        Ben Wallace    -1  PF         0.0         26.199726
8484       LeBron James     2  SF       148.0         22.207167
8134        Paul Pierce  -1.0  SF         0.0         17.737003
8426        Kobe Bryant     7  SG        43.0         17.668943
8558         Jason Kidd    -1  PG         0.0         16.229355
8442  Metta World Peace     5  SF        54.0         12.624950

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2010
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 215.52328821172833
R-squared (XGBoost): 0.7019370779238387

            Player_name Rank Pos  Points_won  Predicted_points
8018      Dwight Howard    1   C       576.0        331.672485
7911          Raja Bell   -1  SG         0.0        100.002686
7905          Raja Bell   -1  SG         0.0         99.816605
8041       LeBron James    4  SF        61.0         50.260967
8050  Metta World Peace    6  SF        29.0         22.029634
7544        Dwyane Wade  10T  SG        13.0         20.505564
7553         Josh Smith    2  PF       136.0         16.347208
7564        Kobe Bryant   12  SG         9.0         15.417433
7797       Marcus Camby  10T  PF        13.0         12.302364
7939      Kevin Garnett   -1  PF         0.0         11.742357

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2011
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 242.6278629310965
R-squared (XGBoost): 0.6355788027475915

         Player_name  Rank Pos  Points_won  Predicted_points
7366   Dwight Howard     1   C       585.0        321.104736
7121   Kevin Garnett     2  PF        77.0        286.468658
7231      Chris Paul   12T  PG        13.0         72.367615
7400       Luol Deng  10.0  SF        24.0         60.580414
7288     Dwyane Wade    16  SG         8.0         48.117401
7508      Josh Smith    25  PF         1.0         44.673393
7523    Andrew Bogut   6.0   C        32.0         43.711838
7186    LeBron James     9  SF        25.0         32.496338
7270    Shawn Marion    -1  SF         0.0         25.262701
7391  Tyson Chandler     3   C        70.0         21.254738

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2012
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 406.5327770023515
R-squared (XGBoost): 0.101683807483395

         Player_name  Rank Pos  Points_won  Predicted_points
6523  Andre Iguodala     7  SF        33.0         34.128017
6527     Serge Ibaka   2.0  PF       294.0         31.700790
6938      Marc Gasol   12T   C         5.0         28.968531
6779     Dwyane Wade   18T  SG         1.0         20.982342
6874     Paul George  -1.0  SG         0.0         20.947380
6599     Ricky Rubio  -1.0  PG         0.0         20.049862
6747      Josh Smith    10  PF         9.0         19.810595
6958      Tony Allen   6.0  SG        36.0         18.657326
6572    LeBron James     4  SF       112.0         15.486906
6620   Kenyon Martin    -1  PF         0.0         13.712017

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2013
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 122.03733070774277
R-squared (XGBoost): 0.4927294468452995

         Player_name Rank Pos  Points_won  Predicted_points
6217      Marc Gasol    1   C       212.0        328.611389
6005     Serge Ibaka  3.0  PF       122.0        162.827103
6355  Tyson Chandler   13   C        11.0        101.097954
6242     Paul George  8.0  SF        57.0         91.948631
6245   Shane Battier   -1  SF         0.0         69.431999
6419      Tim Duncan    6   C        94.0         62.257103
6084    LeBron James    2  PF       149.0         60.940189
5996   Dwight Howard   14   C         9.0         58.578369
6094     Mike Conley   21  PG         1.0         46.142700
6206   Larry Sanders  7.0   C        90.0         36.588146

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2014
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 138.36586151087997
R-squared (XGBoost): 0.7892578480542092

           Player_name  Rank Pos  Points_won  Predicted_points
5847       Joakim Noah   1.0   C       555.0        336.915863
5804       Serge Ibaka   4.0  PF        79.0        108.288513
5898    DeAndre Jordan   3.0   C       121.0         78.775230
5952       Paul George   7.0  SF        30.0         66.596497
5754     Dwight Howard    8T   C        25.0         55.238621
5805    Andre Iguodala     5  SF        47.0         53.222782
5624     Anthony Davis    8T  PF        25.0         38.152992
5641        Chris Paul   13T  PG         5.0         37.114864
5948       Roy Hibbert   2.0   C       166.0         24.191568
5597  DeMarcus Cousins  -1.0   C         0.0         21.218164

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2015
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 258.5764981260845
R-squared (XGBoost): 0.49056697757831436

           Player_name  Rank Pos  Points_won  Predicted_points
5314     Kawhi Leonard     1  SF       333.0        146.532837
5011    DeAndre Jordan   3.0   C       261.0        109.529877
5393     Anthony Davis     4  PF       107.0        104.663582
4908     Kevin Garnett    -1  PF         0.0         71.827354
5134       Rudy Gobert   5.0   C        33.0         70.125328
5107    Draymond Green     2  PF       317.0         42.937531
4890        Marc Gasol   10T   C         7.0         41.419556
5076      Nerlens Noel   15T   C         1.0         40.362568
5031  Hassan Whiteside   15T   C         1.0         37.732925
5017      Paul Millsap  -1.0  PF         0.0         35.867218

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2016
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 339.91894403266247
R-squared (XGBoost): 0.6292677169437575

            Player_name  Rank Pos  Points_won  Predicted_points
4426      Kawhi Leonard     1  SF       547.0        288.982483
4570   Hassan Whiteside     3   C        83.0        213.055191
4474     DeAndre Jordan   4.0   C        50.0        176.066422
4597     Draymond Green     2  PF       421.0        158.564819
4820     Andre Drummond    10   C         3.0         74.423470
4782         Tim Duncan    -1   C         0.0         56.833870
4773       Andrew Bogut  -1.0   C         0.0         24.637062
4667  Russell Westbrook    -1  PG         0.0         20.446465
4464     Andre Iguodala    -1  SF         0.0         14.861508
4524       LeBron James   11T  SF         2.0         14.056814

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2017
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 135.85644395602745
R-squared (XGBoost): 0.7481657852706725

                 Player_name  Rank Pos  Points_won  Predicted_points
3989          Draymond Green     1  PF       434.0        401.683014
3977             Rudy Gobert   2.0   C       269.0         73.456238
4131             Edy Tavares  -1.0   C         0.0         56.987076
3870        Hassan Whiteside    5T   C         3.0         47.531704
4129           Anthony Davis    -1   C         0.0         39.112663
4268           Kawhi Leonard     3  SF       182.0         23.474730
4212   Giannis Antetokounmpo  -1.0  SF         0.0         22.287079
3988       Russell Westbrook    -1  PG         0.0         20.181850
4127  Michael Kidd-Gilchrist  -1.0  SF         0.0         15.473082
4134             Edy Tavares  -1.0   C         0.0         14.711597

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2018
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 285.3342050389231
R-squared (XGBoost): 0.34905131835206193

           Player_name  Rank Pos  Points_won  Predicted_points
3403       Rudy Gobert   1.0   C       466.0        104.825508
3655  Robert Covington   8.0  SF         8.0         80.570084
3177     Anthony Davis     3  PF       139.0         74.627983
3270    Draymond Green     6  PF        20.0         45.050838
3324    Andre Drummond   15T   C         1.0         24.261726
3598    Victor Oladipo   15T  SG         1.0         19.964039
3583      Clint Capela  14.0   C         2.0         19.459650
3180      LeBron James    -1  PF         0.0         17.473669
3661  DeMarcus Cousins  -1.0   C         0.0         17.249712
3391       P.J. Tucker  -1.0  PF         0.0         15.072495

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2019
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 78.34068723326587
R-squared (XGBoost): 0.8191979785353568

                Player_name  Rank Pos  Points_won  Predicted_points
2825            Rudy Gobert   1.0   C       411.0        519.255310
3114  Giannis Antetokounmpo   2.0  PF       280.0        173.611435
2738            Brook Lopez  -1.0   C         0.0         73.022682
2932            Paul George   3.0  SF       150.0         69.865135
2980             Marc Gasol    -1   C         0.0         69.290298
2562           Myles Turner   5.0   C        15.0         64.669853
2979             Marc Gasol    -1   C         0.0         59.077991
2671          Anthony Davis    -1   C         0.0         36.246159
2876         Draymond Green    6T  PF         6.0         24.383631
2702          Kawhi Leonard    6T  SF         6.0         24.257936

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2020
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 115.08588096206614
R-squared (XGBoost): 0.7401193217312894

                Player_name  Rank Pos  Points_won  Predicted_points
2524            Rudy Gobert   3.0   C       187.0        237.507065
2127  Giannis Antetokounmpo   1.0  PF       432.0        228.397400
2270          Anthony Davis     2  PF       200.0        128.534882
2198          Kawhi Leonard    8T  SF         5.0         97.317017
2094            Brook Lopez  10.0   C         4.0         52.755039
2063        Wesley Matthews  -1.0  SG         0.0         51.692238
2017       Hassan Whiteside    11   C         3.0         51.149288
2326           Myles Turner  -1.0   C         0.0         22.788441
2073             Kevin Love  -1.0  PF         0.0         17.046364
2259           LeBron James    -1  PG         0.0         14.906222

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2021
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 242.79161158637112
R-squared (XGBoost): 0.49913820423419575

                Player_name  Rank Pos  Points_won  Predicted_points
1379            Rudy Gobert   1.0   C       464.0        214.168335
1895  Giannis Antetokounmpo   5.0  PF        12.0         77.868736
1719           Myles Turner   9.0   C         3.0         71.368042
1716           Clint Capela   6.0   C        10.0         70.200371
1422         Draymond Green     3  PF        76.0         32.295059
1517           LeBron James    -1  PG         0.0         18.829876
1741       Matisse Thybulle   11T  SG         1.0         18.283257
1785            Ben Simmons   2.0  PG       287.0         16.953491
1554            Mike Conley    -1  PG         0.0         16.739819
1526            Brook Lopez  -1.0   C         0.0         11.544604

---------------------------------------------------------------------
Selected Features Top  50  Test year :  2022
DataFrame does not contain missing values or empty strings/spaces.
DataFrame does not contain missing values or empty strings/spaces.
Mean Squared Error (XGBoost): 162.02192355118052
R-squared (XGBoost): 0.24716449085321324

                Player_name  Rank Pos  Points_won  Predicted_points
1022            Rudy Gobert   3.0   C       136.0        199.986771
1111  Giannis Antetokounmpo   6.0  PF        58.0         51.198513
992             Paul George  -1.0  PF         0.0         48.209618
997       Jaren Jackson Jr.   5.0  PF        99.0         37.611469
610      Michael Porter Jr.  -1.0  SF         0.0         34.611408
713            Marcus Smart     1  PG       257.0         31.592712
1123         Draymond Green    10  PF         2.0         31.000763
627            Clint Capela  -1.0   C         0.0         30.187098
1007            Joel Embiid    -1   C         0.0         22.514902
1306            Bam Adebayo   4.0   C       128.0         22.141567

---------------------------------------------------------------------

,Rank_1994,Rank_1995,Rank_1996,Rank_1997,Rank_1998,Rank_1999,Rank_2000,Rank_2001,Rank_2002,Rank_2003,...,Rank_2013,Rank_2014,Rank_2015,Rank_2016,Rank_2017,Rank_2018,Rank_2019,Rank_2020,Rank_2021,Rank_2022
0,1,1,3,2,1,-1,1,-1,-1,1,...,1,1.0,1,1,1,1.0,1.0,3.0,1.0,3.0
1,2,2,6,-1,2,1,5T,1,1,-1,...,3.0,4.0,3.0,3,2.0,8.0,2.0,1.0,5.0,6.0
2,4,3,-1.0,1,5T,4,2,1,-1,13T,...,13,3.0,4,4.0,-1.0,3,-1.0,2,9.0,-1.0
3,7T,4,1,5,3,5T,3T,8T,2,4,...,8.0,7.0,-1,2,5T,6,3.0,8T,6.0,5.0
4,-1,6T,4,4,4,-1,7,7,3T,-1,...,-1,8T,5.0,10,-1,15T,-1,10.0,3,-1.0
5,9,5,5,6T,9T,-1,3T,2,-1,5.0,...,6,5,2,-1,3,15T,5.0,-1.0,-1,1
6,3,6T,2,-1,5T,7T,8T,11T,3T,3,...,2,8T,10T,-1.0,-1.0,14.0,-1,11,11T,10
7,10,-1,7,3,5T,2,-1,11T,-1,-1.0,...,14,13T,15T,-1,-1,-1,-1,-1.0,2.0,-1.0
8,6,-1,8T,-1.0,11T,7T,8T,3,-1,11,...,21,2.0,15T,-1,-1.0,-1.0,6T,-1.0,-1,-1
9,-1,-1,-1,-1,-1,-1.0,8T,5T,-1,6,...,7.0,-1.0,-1.0,11T,-1.0,-1.0,6T,-1,-1.0,4.0

In [19]:
rank_data_10.to_csv('XGB+Per_All_rank_data_10.csv', index=False)
rank_data_20.to_csv('XGB+Per_All_rank_data_20.csv', index=False)
rank_data_30.to_csv('XGB+Per_All_rank_data_30.csv', index=False)
rank_data_40.to_csv('XGB+Per_All_rank_data_40.csv', index=False)
rank_data_50.to_csv('XGB+Per_All_rank_data_50.csv', index=False)